/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookConfigsConfigIdPutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookConfigsConfigIdPutResponse{}

// V1SdkAutomationPlaybookConfigsConfigIdPutResponse struct for V1SdkAutomationPlaybookConfigsConfigIdPutResponse
type V1SdkAutomationPlaybookConfigsConfigIdPutResponse struct {
	Errors []SdkAutomationValidationError `json:"errors,omitempty"`
	// True when validation succeeded and the update was applied
	IsValid *bool `json:"isValid,omitempty"`
}

// NewV1SdkAutomationPlaybookConfigsConfigIdPutResponse instantiates a new V1SdkAutomationPlaybookConfigsConfigIdPutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookConfigsConfigIdPutResponse() *V1SdkAutomationPlaybookConfigsConfigIdPutResponse {
	this := V1SdkAutomationPlaybookConfigsConfigIdPutResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookConfigsConfigIdPutResponseWithDefaults instantiates a new V1SdkAutomationPlaybookConfigsConfigIdPutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookConfigsConfigIdPutResponseWithDefaults() *V1SdkAutomationPlaybookConfigsConfigIdPutResponse {
	this := V1SdkAutomationPlaybookConfigsConfigIdPutResponse{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutResponse) GetErrors() []SdkAutomationValidationError {
	if o == nil || IsNil(o.Errors) {
		var ret []SdkAutomationValidationError
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutResponse) GetErrorsOk() ([]SdkAutomationValidationError, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []SdkAutomationValidationError and assigns it to the Errors field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutResponse) SetErrors(v []SdkAutomationValidationError) {
	o.Errors = v
}

// GetIsValid returns the IsValid field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutResponse) GetIsValid() bool {
	if o == nil || IsNil(o.IsValid) {
		var ret bool
		return ret
	}
	return *o.IsValid
}

// GetIsValidOk returns a tuple with the IsValid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutResponse) GetIsValidOk() (*bool, bool) {
	if o == nil || IsNil(o.IsValid) {
		return nil, false
	}
	return o.IsValid, true
}

// HasIsValid returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutResponse) HasIsValid() bool {
	if o != nil && !IsNil(o.IsValid) {
		return true
	}

	return false
}

// SetIsValid gets a reference to the given bool and assigns it to the IsValid field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutResponse) SetIsValid(v bool) {
	o.IsValid = &v
}

func (o V1SdkAutomationPlaybookConfigsConfigIdPutResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookConfigsConfigIdPutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.IsValid) {
		toSerialize["isValid"] = o.IsValid
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookConfigsConfigIdPutResponse struct {
	value *V1SdkAutomationPlaybookConfigsConfigIdPutResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdPutResponse) Get() *V1SdkAutomationPlaybookConfigsConfigIdPutResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdPutResponse) Set(val *V1SdkAutomationPlaybookConfigsConfigIdPutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdPutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdPutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookConfigsConfigIdPutResponse(val *V1SdkAutomationPlaybookConfigsConfigIdPutResponse) *NullableV1SdkAutomationPlaybookConfigsConfigIdPutResponse {
	return &NullableV1SdkAutomationPlaybookConfigsConfigIdPutResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdPutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdPutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


