/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the SdkAutomationPlaybookConfigSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SdkAutomationPlaybookConfigSummary{}

// SdkAutomationPlaybookConfigSummary struct for SdkAutomationPlaybookConfigSummary
type SdkAutomationPlaybookConfigSummary struct {
	// Config id
	ConfigId *string `json:"configId,omitempty"`
	// IAM user id of the config creator; UI resolves the display name
	CreatedByUserId *string `json:"createdByUserId,omitempty"`
	// Latest run status; unset when the config has no run yet
	JobStatus *string `json:"jobStatus,omitempty"`
	// Display name
	Name *string `json:"name,omitempty"`
	// Latest job id for this config; empty if never run
	RunId *string `json:"runId,omitempty"`
	// Per-config run counter; 0 if never run
	RunNumber *int32 `json:"runNumber,omitempty"`
	StartedAt *GoogleProtobufTimestamp `json:"startedAt,omitempty"`
	// IAM user id of who launched the latest run
	StartedByUserId *string `json:"startedByUserId,omitempty"`
	// Config lifecycle status
	Status *string `json:"status,omitempty"`
	UpdatedAt *GoogleProtobufTimestamp `json:"updatedAt,omitempty"`
}

// NewSdkAutomationPlaybookConfigSummary instantiates a new SdkAutomationPlaybookConfigSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSdkAutomationPlaybookConfigSummary() *SdkAutomationPlaybookConfigSummary {
	this := SdkAutomationPlaybookConfigSummary{}
	return &this
}

// NewSdkAutomationPlaybookConfigSummaryWithDefaults instantiates a new SdkAutomationPlaybookConfigSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSdkAutomationPlaybookConfigSummaryWithDefaults() *SdkAutomationPlaybookConfigSummary {
	this := SdkAutomationPlaybookConfigSummary{}
	return &this
}

// GetConfigId returns the ConfigId field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfigSummary) GetConfigId() string {
	if o == nil || IsNil(o.ConfigId) {
		var ret string
		return ret
	}
	return *o.ConfigId
}

// GetConfigIdOk returns a tuple with the ConfigId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfigSummary) GetConfigIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConfigId) {
		return nil, false
	}
	return o.ConfigId, true
}

// HasConfigId returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfigSummary) HasConfigId() bool {
	if o != nil && !IsNil(o.ConfigId) {
		return true
	}

	return false
}

// SetConfigId gets a reference to the given string and assigns it to the ConfigId field.
func (o *SdkAutomationPlaybookConfigSummary) SetConfigId(v string) {
	o.ConfigId = &v
}

// GetCreatedByUserId returns the CreatedByUserId field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfigSummary) GetCreatedByUserId() string {
	if o == nil || IsNil(o.CreatedByUserId) {
		var ret string
		return ret
	}
	return *o.CreatedByUserId
}

// GetCreatedByUserIdOk returns a tuple with the CreatedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfigSummary) GetCreatedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByUserId) {
		return nil, false
	}
	return o.CreatedByUserId, true
}

// HasCreatedByUserId returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfigSummary) HasCreatedByUserId() bool {
	if o != nil && !IsNil(o.CreatedByUserId) {
		return true
	}

	return false
}

// SetCreatedByUserId gets a reference to the given string and assigns it to the CreatedByUserId field.
func (o *SdkAutomationPlaybookConfigSummary) SetCreatedByUserId(v string) {
	o.CreatedByUserId = &v
}

// GetJobStatus returns the JobStatus field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfigSummary) GetJobStatus() string {
	if o == nil || IsNil(o.JobStatus) {
		var ret string
		return ret
	}
	return *o.JobStatus
}

// GetJobStatusOk returns a tuple with the JobStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfigSummary) GetJobStatusOk() (*string, bool) {
	if o == nil || IsNil(o.JobStatus) {
		return nil, false
	}
	return o.JobStatus, true
}

// HasJobStatus returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfigSummary) HasJobStatus() bool {
	if o != nil && !IsNil(o.JobStatus) {
		return true
	}

	return false
}

// SetJobStatus gets a reference to the given string and assigns it to the JobStatus field.
func (o *SdkAutomationPlaybookConfigSummary) SetJobStatus(v string) {
	o.JobStatus = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfigSummary) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfigSummary) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfigSummary) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SdkAutomationPlaybookConfigSummary) SetName(v string) {
	o.Name = &v
}

// GetRunId returns the RunId field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfigSummary) GetRunId() string {
	if o == nil || IsNil(o.RunId) {
		var ret string
		return ret
	}
	return *o.RunId
}

// GetRunIdOk returns a tuple with the RunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfigSummary) GetRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.RunId) {
		return nil, false
	}
	return o.RunId, true
}

// HasRunId returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfigSummary) HasRunId() bool {
	if o != nil && !IsNil(o.RunId) {
		return true
	}

	return false
}

// SetRunId gets a reference to the given string and assigns it to the RunId field.
func (o *SdkAutomationPlaybookConfigSummary) SetRunId(v string) {
	o.RunId = &v
}

// GetRunNumber returns the RunNumber field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfigSummary) GetRunNumber() int32 {
	if o == nil || IsNil(o.RunNumber) {
		var ret int32
		return ret
	}
	return *o.RunNumber
}

// GetRunNumberOk returns a tuple with the RunNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfigSummary) GetRunNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.RunNumber) {
		return nil, false
	}
	return o.RunNumber, true
}

// HasRunNumber returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfigSummary) HasRunNumber() bool {
	if o != nil && !IsNil(o.RunNumber) {
		return true
	}

	return false
}

// SetRunNumber gets a reference to the given int32 and assigns it to the RunNumber field.
func (o *SdkAutomationPlaybookConfigSummary) SetRunNumber(v int32) {
	o.RunNumber = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfigSummary) GetStartedAt() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.StartedAt) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfigSummary) GetStartedAtOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfigSummary) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given GoogleProtobufTimestamp and assigns it to the StartedAt field.
func (o *SdkAutomationPlaybookConfigSummary) SetStartedAt(v GoogleProtobufTimestamp) {
	o.StartedAt = &v
}

// GetStartedByUserId returns the StartedByUserId field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfigSummary) GetStartedByUserId() string {
	if o == nil || IsNil(o.StartedByUserId) {
		var ret string
		return ret
	}
	return *o.StartedByUserId
}

// GetStartedByUserIdOk returns a tuple with the StartedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfigSummary) GetStartedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.StartedByUserId) {
		return nil, false
	}
	return o.StartedByUserId, true
}

// HasStartedByUserId returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfigSummary) HasStartedByUserId() bool {
	if o != nil && !IsNil(o.StartedByUserId) {
		return true
	}

	return false
}

// SetStartedByUserId gets a reference to the given string and assigns it to the StartedByUserId field.
func (o *SdkAutomationPlaybookConfigSummary) SetStartedByUserId(v string) {
	o.StartedByUserId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfigSummary) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfigSummary) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfigSummary) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SdkAutomationPlaybookConfigSummary) SetStatus(v string) {
	o.Status = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfigSummary) GetUpdatedAt() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfigSummary) GetUpdatedAtOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfigSummary) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given GoogleProtobufTimestamp and assigns it to the UpdatedAt field.
func (o *SdkAutomationPlaybookConfigSummary) SetUpdatedAt(v GoogleProtobufTimestamp) {
	o.UpdatedAt = &v
}

func (o SdkAutomationPlaybookConfigSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SdkAutomationPlaybookConfigSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConfigId) {
		toSerialize["configId"] = o.ConfigId
	}
	if !IsNil(o.CreatedByUserId) {
		toSerialize["createdByUserId"] = o.CreatedByUserId
	}
	if !IsNil(o.JobStatus) {
		toSerialize["jobStatus"] = o.JobStatus
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RunId) {
		toSerialize["runId"] = o.RunId
	}
	if !IsNil(o.RunNumber) {
		toSerialize["runNumber"] = o.RunNumber
	}
	if !IsNil(o.StartedAt) {
		toSerialize["startedAt"] = o.StartedAt
	}
	if !IsNil(o.StartedByUserId) {
		toSerialize["startedByUserId"] = o.StartedByUserId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableSdkAutomationPlaybookConfigSummary struct {
	value *SdkAutomationPlaybookConfigSummary
	isSet bool
}

func (v NullableSdkAutomationPlaybookConfigSummary) Get() *SdkAutomationPlaybookConfigSummary {
	return v.value
}

func (v *NullableSdkAutomationPlaybookConfigSummary) Set(val *SdkAutomationPlaybookConfigSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableSdkAutomationPlaybookConfigSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableSdkAutomationPlaybookConfigSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSdkAutomationPlaybookConfigSummary(val *SdkAutomationPlaybookConfigSummary) *NullableSdkAutomationPlaybookConfigSummary {
	return &NullableSdkAutomationPlaybookConfigSummary{value: val, isSet: true}
}

func (v NullableSdkAutomationPlaybookConfigSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSdkAutomationPlaybookConfigSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


