/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the SdkAutomationCatalogModuleSlot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SdkAutomationCatalogModuleSlot{}

// SdkAutomationCatalogModuleSlot struct for SdkAutomationCatalogModuleSlot
type SdkAutomationCatalogModuleSlot struct {
	// Owning catalog playbook key (e.g. system_bundle)
	BundleKey *string `json:"bundleKey,omitempty"`
	// Short description of the module slot
	Description *string `json:"description,omitempty"`
	// Top-level YAML key from playbook_catalog_module the UI uses to map an uploaded file to this module (e.g. device_system, interfaces, circuits)
	FileDistinguisher *string `json:"fileDistinguisher,omitempty"`
	// When true, create/validate must include this module_key
	IsRequired *bool `json:"isRequired,omitempty"`
	// Stable catalog key from playbook_catalog_module (e.g. system_config_file); used as ModuleFile.module_key
	ModuleKey *string `json:"moduleKey,omitempty"`
	// Display name for the module slot
	Name *string `json:"name,omitempty"`
}

// NewSdkAutomationCatalogModuleSlot instantiates a new SdkAutomationCatalogModuleSlot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSdkAutomationCatalogModuleSlot() *SdkAutomationCatalogModuleSlot {
	this := SdkAutomationCatalogModuleSlot{}
	return &this
}

// NewSdkAutomationCatalogModuleSlotWithDefaults instantiates a new SdkAutomationCatalogModuleSlot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSdkAutomationCatalogModuleSlotWithDefaults() *SdkAutomationCatalogModuleSlot {
	this := SdkAutomationCatalogModuleSlot{}
	return &this
}

// GetBundleKey returns the BundleKey field value if set, zero value otherwise.
func (o *SdkAutomationCatalogModuleSlot) GetBundleKey() string {
	if o == nil || IsNil(o.BundleKey) {
		var ret string
		return ret
	}
	return *o.BundleKey
}

// GetBundleKeyOk returns a tuple with the BundleKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationCatalogModuleSlot) GetBundleKeyOk() (*string, bool) {
	if o == nil || IsNil(o.BundleKey) {
		return nil, false
	}
	return o.BundleKey, true
}

// HasBundleKey returns a boolean if a field has been set.
func (o *SdkAutomationCatalogModuleSlot) HasBundleKey() bool {
	if o != nil && !IsNil(o.BundleKey) {
		return true
	}

	return false
}

// SetBundleKey gets a reference to the given string and assigns it to the BundleKey field.
func (o *SdkAutomationCatalogModuleSlot) SetBundleKey(v string) {
	o.BundleKey = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SdkAutomationCatalogModuleSlot) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationCatalogModuleSlot) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SdkAutomationCatalogModuleSlot) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SdkAutomationCatalogModuleSlot) SetDescription(v string) {
	o.Description = &v
}

// GetFileDistinguisher returns the FileDistinguisher field value if set, zero value otherwise.
func (o *SdkAutomationCatalogModuleSlot) GetFileDistinguisher() string {
	if o == nil || IsNil(o.FileDistinguisher) {
		var ret string
		return ret
	}
	return *o.FileDistinguisher
}

// GetFileDistinguisherOk returns a tuple with the FileDistinguisher field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationCatalogModuleSlot) GetFileDistinguisherOk() (*string, bool) {
	if o == nil || IsNil(o.FileDistinguisher) {
		return nil, false
	}
	return o.FileDistinguisher, true
}

// HasFileDistinguisher returns a boolean if a field has been set.
func (o *SdkAutomationCatalogModuleSlot) HasFileDistinguisher() bool {
	if o != nil && !IsNil(o.FileDistinguisher) {
		return true
	}

	return false
}

// SetFileDistinguisher gets a reference to the given string and assigns it to the FileDistinguisher field.
func (o *SdkAutomationCatalogModuleSlot) SetFileDistinguisher(v string) {
	o.FileDistinguisher = &v
}

// GetIsRequired returns the IsRequired field value if set, zero value otherwise.
func (o *SdkAutomationCatalogModuleSlot) GetIsRequired() bool {
	if o == nil || IsNil(o.IsRequired) {
		var ret bool
		return ret
	}
	return *o.IsRequired
}

// GetIsRequiredOk returns a tuple with the IsRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationCatalogModuleSlot) GetIsRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRequired) {
		return nil, false
	}
	return o.IsRequired, true
}

// HasIsRequired returns a boolean if a field has been set.
func (o *SdkAutomationCatalogModuleSlot) HasIsRequired() bool {
	if o != nil && !IsNil(o.IsRequired) {
		return true
	}

	return false
}

// SetIsRequired gets a reference to the given bool and assigns it to the IsRequired field.
func (o *SdkAutomationCatalogModuleSlot) SetIsRequired(v bool) {
	o.IsRequired = &v
}

// GetModuleKey returns the ModuleKey field value if set, zero value otherwise.
func (o *SdkAutomationCatalogModuleSlot) GetModuleKey() string {
	if o == nil || IsNil(o.ModuleKey) {
		var ret string
		return ret
	}
	return *o.ModuleKey
}

// GetModuleKeyOk returns a tuple with the ModuleKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationCatalogModuleSlot) GetModuleKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ModuleKey) {
		return nil, false
	}
	return o.ModuleKey, true
}

// HasModuleKey returns a boolean if a field has been set.
func (o *SdkAutomationCatalogModuleSlot) HasModuleKey() bool {
	if o != nil && !IsNil(o.ModuleKey) {
		return true
	}

	return false
}

// SetModuleKey gets a reference to the given string and assigns it to the ModuleKey field.
func (o *SdkAutomationCatalogModuleSlot) SetModuleKey(v string) {
	o.ModuleKey = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SdkAutomationCatalogModuleSlot) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationCatalogModuleSlot) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SdkAutomationCatalogModuleSlot) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SdkAutomationCatalogModuleSlot) SetName(v string) {
	o.Name = &v
}

func (o SdkAutomationCatalogModuleSlot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SdkAutomationCatalogModuleSlot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BundleKey) {
		toSerialize["bundleKey"] = o.BundleKey
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.FileDistinguisher) {
		toSerialize["fileDistinguisher"] = o.FileDistinguisher
	}
	if !IsNil(o.IsRequired) {
		toSerialize["isRequired"] = o.IsRequired
	}
	if !IsNil(o.ModuleKey) {
		toSerialize["moduleKey"] = o.ModuleKey
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableSdkAutomationCatalogModuleSlot struct {
	value *SdkAutomationCatalogModuleSlot
	isSet bool
}

func (v NullableSdkAutomationCatalogModuleSlot) Get() *SdkAutomationCatalogModuleSlot {
	return v.value
}

func (v *NullableSdkAutomationCatalogModuleSlot) Set(val *SdkAutomationCatalogModuleSlot) {
	v.value = val
	v.isSet = true
}

func (v NullableSdkAutomationCatalogModuleSlot) IsSet() bool {
	return v.isSet
}

func (v *NullableSdkAutomationCatalogModuleSlot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSdkAutomationCatalogModuleSlot(val *SdkAutomationCatalogModuleSlot) *NullableSdkAutomationCatalogModuleSlot {
	return &NullableSdkAutomationCatalogModuleSlot{value: val, isSet: true}
}

func (v NullableSdkAutomationCatalogModuleSlot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSdkAutomationCatalogModuleSlot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


