/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the CommonUserInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonUserInfo{}

// CommonUserInfo struct for CommonUserInfo
type CommonUserInfo struct {
	BearerToken *string `json:"bearerToken,omitempty"`
	EnterpriseId *int64 `json:"enterpriseId,omitempty"`
	Exp *int64 `json:"exp,omitempty"`
	OriginalEnterpriseId *int64 `json:"originalEnterpriseId,omitempty"`
	Permissions *CommonPermissions `json:"permissions,omitempty"`
	TimeZone *string `json:"timeZone,omitempty"`
	UserId *string `json:"userId,omitempty"`
}

// NewCommonUserInfo instantiates a new CommonUserInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonUserInfo() *CommonUserInfo {
	this := CommonUserInfo{}
	return &this
}

// NewCommonUserInfoWithDefaults instantiates a new CommonUserInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonUserInfoWithDefaults() *CommonUserInfo {
	this := CommonUserInfo{}
	return &this
}

// GetBearerToken returns the BearerToken field value if set, zero value otherwise.
func (o *CommonUserInfo) GetBearerToken() string {
	if o == nil || IsNil(o.BearerToken) {
		var ret string
		return ret
	}
	return *o.BearerToken
}

// GetBearerTokenOk returns a tuple with the BearerToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonUserInfo) GetBearerTokenOk() (*string, bool) {
	if o == nil || IsNil(o.BearerToken) {
		return nil, false
	}
	return o.BearerToken, true
}

// HasBearerToken returns a boolean if a field has been set.
func (o *CommonUserInfo) HasBearerToken() bool {
	if o != nil && !IsNil(o.BearerToken) {
		return true
	}

	return false
}

// SetBearerToken gets a reference to the given string and assigns it to the BearerToken field.
func (o *CommonUserInfo) SetBearerToken(v string) {
	o.BearerToken = &v
}

// GetEnterpriseId returns the EnterpriseId field value if set, zero value otherwise.
func (o *CommonUserInfo) GetEnterpriseId() int64 {
	if o == nil || IsNil(o.EnterpriseId) {
		var ret int64
		return ret
	}
	return *o.EnterpriseId
}

// GetEnterpriseIdOk returns a tuple with the EnterpriseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonUserInfo) GetEnterpriseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.EnterpriseId) {
		return nil, false
	}
	return o.EnterpriseId, true
}

// HasEnterpriseId returns a boolean if a field has been set.
func (o *CommonUserInfo) HasEnterpriseId() bool {
	if o != nil && !IsNil(o.EnterpriseId) {
		return true
	}

	return false
}

// SetEnterpriseId gets a reference to the given int64 and assigns it to the EnterpriseId field.
func (o *CommonUserInfo) SetEnterpriseId(v int64) {
	o.EnterpriseId = &v
}

// GetExp returns the Exp field value if set, zero value otherwise.
func (o *CommonUserInfo) GetExp() int64 {
	if o == nil || IsNil(o.Exp) {
		var ret int64
		return ret
	}
	return *o.Exp
}

// GetExpOk returns a tuple with the Exp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonUserInfo) GetExpOk() (*int64, bool) {
	if o == nil || IsNil(o.Exp) {
		return nil, false
	}
	return o.Exp, true
}

// HasExp returns a boolean if a field has been set.
func (o *CommonUserInfo) HasExp() bool {
	if o != nil && !IsNil(o.Exp) {
		return true
	}

	return false
}

// SetExp gets a reference to the given int64 and assigns it to the Exp field.
func (o *CommonUserInfo) SetExp(v int64) {
	o.Exp = &v
}

// GetOriginalEnterpriseId returns the OriginalEnterpriseId field value if set, zero value otherwise.
func (o *CommonUserInfo) GetOriginalEnterpriseId() int64 {
	if o == nil || IsNil(o.OriginalEnterpriseId) {
		var ret int64
		return ret
	}
	return *o.OriginalEnterpriseId
}

// GetOriginalEnterpriseIdOk returns a tuple with the OriginalEnterpriseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonUserInfo) GetOriginalEnterpriseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.OriginalEnterpriseId) {
		return nil, false
	}
	return o.OriginalEnterpriseId, true
}

// HasOriginalEnterpriseId returns a boolean if a field has been set.
func (o *CommonUserInfo) HasOriginalEnterpriseId() bool {
	if o != nil && !IsNil(o.OriginalEnterpriseId) {
		return true
	}

	return false
}

// SetOriginalEnterpriseId gets a reference to the given int64 and assigns it to the OriginalEnterpriseId field.
func (o *CommonUserInfo) SetOriginalEnterpriseId(v int64) {
	o.OriginalEnterpriseId = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *CommonUserInfo) GetPermissions() CommonPermissions {
	if o == nil || IsNil(o.Permissions) {
		var ret CommonPermissions
		return ret
	}
	return *o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonUserInfo) GetPermissionsOk() (*CommonPermissions, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *CommonUserInfo) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given CommonPermissions and assigns it to the Permissions field.
func (o *CommonUserInfo) SetPermissions(v CommonPermissions) {
	o.Permissions = &v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *CommonUserInfo) GetTimeZone() string {
	if o == nil || IsNil(o.TimeZone) {
		var ret string
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonUserInfo) GetTimeZoneOk() (*string, bool) {
	if o == nil || IsNil(o.TimeZone) {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *CommonUserInfo) HasTimeZone() bool {
	if o != nil && !IsNil(o.TimeZone) {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given string and assigns it to the TimeZone field.
func (o *CommonUserInfo) SetTimeZone(v string) {
	o.TimeZone = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *CommonUserInfo) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonUserInfo) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *CommonUserInfo) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *CommonUserInfo) SetUserId(v string) {
	o.UserId = &v
}

func (o CommonUserInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonUserInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BearerToken) {
		toSerialize["bearerToken"] = o.BearerToken
	}
	if !IsNil(o.EnterpriseId) {
		toSerialize["enterpriseId"] = o.EnterpriseId
	}
	if !IsNil(o.Exp) {
		toSerialize["exp"] = o.Exp
	}
	if !IsNil(o.OriginalEnterpriseId) {
		toSerialize["originalEnterpriseId"] = o.OriginalEnterpriseId
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	if !IsNil(o.TimeZone) {
		toSerialize["timeZone"] = o.TimeZone
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	return toSerialize, nil
}

type NullableCommonUserInfo struct {
	value *CommonUserInfo
	isSet bool
}

func (v NullableCommonUserInfo) Get() *CommonUserInfo {
	return v.value
}

func (v *NullableCommonUserInfo) Set(val *CommonUserInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonUserInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonUserInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonUserInfo(val *CommonUserInfo) *NullableCommonUserInfo {
	return &NullableCommonUserInfo{value: val, isSet: true}
}

func (v NullableCommonUserInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonUserInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


