/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse{}

// V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse struct for V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse
type V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse struct {
	// Config status after staging (typically STAGED)
	Status *string `json:"status,omitempty"`
}

// NewV1SdkAutomationPlaybookConfigsConfigIdStagePutResponse instantiates a new V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookConfigsConfigIdStagePutResponse() *V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse {
	this := V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookConfigsConfigIdStagePutResponseWithDefaults instantiates a new V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookConfigsConfigIdStagePutResponseWithDefaults() *V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse {
	this := V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) SetStatus(v string) {
	o.Status = &v
}

func (o V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutResponse struct {
	value *V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) Get() *V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) Set(val *V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookConfigsConfigIdStagePutResponse(val *V1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) *NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutResponse {
	return &NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


