/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookJobsJobIdRunPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookJobsJobIdRunPostResponse{}

// V1SdkAutomationPlaybookJobsJobIdRunPostResponse struct for V1SdkAutomationPlaybookJobsJobIdRunPostResponse
type V1SdkAutomationPlaybookJobsJobIdRunPostResponse struct {
	// Newly created job id for the re-run
	JobId *string `json:"jobId,omitempty"`
	// Initial status of the new job
	Status *string `json:"status,omitempty"`
}

// NewV1SdkAutomationPlaybookJobsJobIdRunPostResponse instantiates a new V1SdkAutomationPlaybookJobsJobIdRunPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookJobsJobIdRunPostResponse() *V1SdkAutomationPlaybookJobsJobIdRunPostResponse {
	this := V1SdkAutomationPlaybookJobsJobIdRunPostResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookJobsJobIdRunPostResponseWithDefaults instantiates a new V1SdkAutomationPlaybookJobsJobIdRunPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookJobsJobIdRunPostResponseWithDefaults() *V1SdkAutomationPlaybookJobsJobIdRunPostResponse {
	this := V1SdkAutomationPlaybookJobsJobIdRunPostResponse{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostResponse) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostResponse) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostResponse) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostResponse) SetJobId(v string) {
	o.JobId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostResponse) SetStatus(v string) {
	o.Status = &v
}

func (o V1SdkAutomationPlaybookJobsJobIdRunPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookJobsJobIdRunPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobId) {
		toSerialize["jobId"] = o.JobId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookJobsJobIdRunPostResponse struct {
	value *V1SdkAutomationPlaybookJobsJobIdRunPostResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdRunPostResponse) Get() *V1SdkAutomationPlaybookJobsJobIdRunPostResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdRunPostResponse) Set(val *V1SdkAutomationPlaybookJobsJobIdRunPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdRunPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdRunPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookJobsJobIdRunPostResponse(val *V1SdkAutomationPlaybookJobsJobIdRunPostResponse) *NullableV1SdkAutomationPlaybookJobsJobIdRunPostResponse {
	return &NullableV1SdkAutomationPlaybookJobsJobIdRunPostResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdRunPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdRunPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


