/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1ExtranetB2bProducerReviewPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bProducerReviewPostRequest{}

// V1ExtranetB2bProducerReviewPostRequest struct for V1ExtranetB2bProducerReviewPostRequest
type V1ExtranetB2bProducerReviewPostRequest struct {
	Policy ManaV2ExtranetServiceProducerPolicy `json:"policy"`
	// Producer service name (letters, digits, hyphens only) (required)
	ServiceName string `json:"serviceName"`
	// Branded extranet service type (peering_service, client_to_server, …) (required)
	ServiceType string `json:"serviceType"`
}

type _V1ExtranetB2bProducerReviewPostRequest V1ExtranetB2bProducerReviewPostRequest

// NewV1ExtranetB2bProducerReviewPostRequest instantiates a new V1ExtranetB2bProducerReviewPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bProducerReviewPostRequest(policy ManaV2ExtranetServiceProducerPolicy, serviceName string, serviceType string) *V1ExtranetB2bProducerReviewPostRequest {
	this := V1ExtranetB2bProducerReviewPostRequest{}
	this.Policy = policy
	this.ServiceName = serviceName
	this.ServiceType = serviceType
	return &this
}

// NewV1ExtranetB2bProducerReviewPostRequestWithDefaults instantiates a new V1ExtranetB2bProducerReviewPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bProducerReviewPostRequestWithDefaults() *V1ExtranetB2bProducerReviewPostRequest {
	this := V1ExtranetB2bProducerReviewPostRequest{}
	return &this
}

// GetPolicy returns the Policy field value
func (o *V1ExtranetB2bProducerReviewPostRequest) GetPolicy() ManaV2ExtranetServiceProducerPolicy {
	if o == nil {
		var ret ManaV2ExtranetServiceProducerPolicy
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bProducerReviewPostRequest) GetPolicyOk() (*ManaV2ExtranetServiceProducerPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Policy, true
}

// SetPolicy sets field value
func (o *V1ExtranetB2bProducerReviewPostRequest) SetPolicy(v ManaV2ExtranetServiceProducerPolicy) {
	o.Policy = v
}

// GetServiceName returns the ServiceName field value
func (o *V1ExtranetB2bProducerReviewPostRequest) GetServiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bProducerReviewPostRequest) GetServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceName, true
}

// SetServiceName sets field value
func (o *V1ExtranetB2bProducerReviewPostRequest) SetServiceName(v string) {
	o.ServiceName = v
}

// GetServiceType returns the ServiceType field value
func (o *V1ExtranetB2bProducerReviewPostRequest) GetServiceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bProducerReviewPostRequest) GetServiceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceType, true
}

// SetServiceType sets field value
func (o *V1ExtranetB2bProducerReviewPostRequest) SetServiceType(v string) {
	o.ServiceType = v
}

func (o V1ExtranetB2bProducerReviewPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bProducerReviewPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy"] = o.Policy
	toSerialize["serviceName"] = o.ServiceName
	toSerialize["serviceType"] = o.ServiceType
	return toSerialize, nil
}

func (o *V1ExtranetB2bProducerReviewPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"policy",
		"serviceName",
		"serviceType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ExtranetB2bProducerReviewPostRequest := _V1ExtranetB2bProducerReviewPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ExtranetB2bProducerReviewPostRequest)

	if err != nil {
		return err
	}

	*o = V1ExtranetB2bProducerReviewPostRequest(varV1ExtranetB2bProducerReviewPostRequest)

	return err
}

type NullableV1ExtranetB2bProducerReviewPostRequest struct {
	value *V1ExtranetB2bProducerReviewPostRequest
	isSet bool
}

func (v NullableV1ExtranetB2bProducerReviewPostRequest) Get() *V1ExtranetB2bProducerReviewPostRequest {
	return v.value
}

func (v *NullableV1ExtranetB2bProducerReviewPostRequest) Set(val *V1ExtranetB2bProducerReviewPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bProducerReviewPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bProducerReviewPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bProducerReviewPostRequest(val *V1ExtranetB2bProducerReviewPostRequest) *NullableV1ExtranetB2bProducerReviewPostRequest {
	return &NullableV1ExtranetB2bProducerReviewPostRequest{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bProducerReviewPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bProducerReviewPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


