/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookJobsJobIdResumePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookJobsJobIdResumePostRequest{}

// V1SdkAutomationPlaybookJobsJobIdResumePostRequest struct for V1SdkAutomationPlaybookJobsJobIdResumePostRequest
type V1SdkAutomationPlaybookJobsJobIdResumePostRequest struct {
	// When true, resume straight into deploy; otherwise resume as a dry-run
	IsDeploy *bool `json:"isDeploy,omitempty"`
	// When true, request ansible -vvv for the resumed phase
	VerboseLogs *bool `json:"verboseLogs,omitempty"`
}

// NewV1SdkAutomationPlaybookJobsJobIdResumePostRequest instantiates a new V1SdkAutomationPlaybookJobsJobIdResumePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookJobsJobIdResumePostRequest() *V1SdkAutomationPlaybookJobsJobIdResumePostRequest {
	this := V1SdkAutomationPlaybookJobsJobIdResumePostRequest{}
	return &this
}

// NewV1SdkAutomationPlaybookJobsJobIdResumePostRequestWithDefaults instantiates a new V1SdkAutomationPlaybookJobsJobIdResumePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookJobsJobIdResumePostRequestWithDefaults() *V1SdkAutomationPlaybookJobsJobIdResumePostRequest {
	this := V1SdkAutomationPlaybookJobsJobIdResumePostRequest{}
	return &this
}

// GetIsDeploy returns the IsDeploy field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostRequest) GetIsDeploy() bool {
	if o == nil || IsNil(o.IsDeploy) {
		var ret bool
		return ret
	}
	return *o.IsDeploy
}

// GetIsDeployOk returns a tuple with the IsDeploy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostRequest) GetIsDeployOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeploy) {
		return nil, false
	}
	return o.IsDeploy, true
}

// HasIsDeploy returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostRequest) HasIsDeploy() bool {
	if o != nil && !IsNil(o.IsDeploy) {
		return true
	}

	return false
}

// SetIsDeploy gets a reference to the given bool and assigns it to the IsDeploy field.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostRequest) SetIsDeploy(v bool) {
	o.IsDeploy = &v
}

// GetVerboseLogs returns the VerboseLogs field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostRequest) GetVerboseLogs() bool {
	if o == nil || IsNil(o.VerboseLogs) {
		var ret bool
		return ret
	}
	return *o.VerboseLogs
}

// GetVerboseLogsOk returns a tuple with the VerboseLogs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostRequest) GetVerboseLogsOk() (*bool, bool) {
	if o == nil || IsNil(o.VerboseLogs) {
		return nil, false
	}
	return o.VerboseLogs, true
}

// HasVerboseLogs returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostRequest) HasVerboseLogs() bool {
	if o != nil && !IsNil(o.VerboseLogs) {
		return true
	}

	return false
}

// SetVerboseLogs gets a reference to the given bool and assigns it to the VerboseLogs field.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostRequest) SetVerboseLogs(v bool) {
	o.VerboseLogs = &v
}

func (o V1SdkAutomationPlaybookJobsJobIdResumePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookJobsJobIdResumePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsDeploy) {
		toSerialize["isDeploy"] = o.IsDeploy
	}
	if !IsNil(o.VerboseLogs) {
		toSerialize["verboseLogs"] = o.VerboseLogs
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookJobsJobIdResumePostRequest struct {
	value *V1SdkAutomationPlaybookJobsJobIdResumePostRequest
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdResumePostRequest) Get() *V1SdkAutomationPlaybookJobsJobIdResumePostRequest {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdResumePostRequest) Set(val *V1SdkAutomationPlaybookJobsJobIdResumePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdResumePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdResumePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookJobsJobIdResumePostRequest(val *V1SdkAutomationPlaybookJobsJobIdResumePostRequest) *NullableV1SdkAutomationPlaybookJobsJobIdResumePostRequest {
	return &NullableV1SdkAutomationPlaybookJobsJobIdResumePostRequest{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdResumePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdResumePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


