/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the SdkAutomationModuleFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SdkAutomationModuleFile{}

// SdkAutomationModuleFile struct for SdkAutomationModuleFile
type SdkAutomationModuleFile struct {
	// YAML file contents
	Content *string `json:"content,omitempty"`
	// Original upload filename (informational; not used for routing)
	Filename *string `json:"filename,omitempty"`
	// Catalog key from playbook_catalog_module (e.g. system_config_file)
	ModuleKey *string `json:"moduleKey,omitempty"`
}

// NewSdkAutomationModuleFile instantiates a new SdkAutomationModuleFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSdkAutomationModuleFile() *SdkAutomationModuleFile {
	this := SdkAutomationModuleFile{}
	return &this
}

// NewSdkAutomationModuleFileWithDefaults instantiates a new SdkAutomationModuleFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSdkAutomationModuleFileWithDefaults() *SdkAutomationModuleFile {
	this := SdkAutomationModuleFile{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *SdkAutomationModuleFile) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationModuleFile) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *SdkAutomationModuleFile) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *SdkAutomationModuleFile) SetContent(v string) {
	o.Content = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *SdkAutomationModuleFile) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationModuleFile) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *SdkAutomationModuleFile) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *SdkAutomationModuleFile) SetFilename(v string) {
	o.Filename = &v
}

// GetModuleKey returns the ModuleKey field value if set, zero value otherwise.
func (o *SdkAutomationModuleFile) GetModuleKey() string {
	if o == nil || IsNil(o.ModuleKey) {
		var ret string
		return ret
	}
	return *o.ModuleKey
}

// GetModuleKeyOk returns a tuple with the ModuleKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationModuleFile) GetModuleKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ModuleKey) {
		return nil, false
	}
	return o.ModuleKey, true
}

// HasModuleKey returns a boolean if a field has been set.
func (o *SdkAutomationModuleFile) HasModuleKey() bool {
	if o != nil && !IsNil(o.ModuleKey) {
		return true
	}

	return false
}

// SetModuleKey gets a reference to the given string and assigns it to the ModuleKey field.
func (o *SdkAutomationModuleFile) SetModuleKey(v string) {
	o.ModuleKey = &v
}

func (o SdkAutomationModuleFile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SdkAutomationModuleFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.ModuleKey) {
		toSerialize["moduleKey"] = o.ModuleKey
	}
	return toSerialize, nil
}

type NullableSdkAutomationModuleFile struct {
	value *SdkAutomationModuleFile
	isSet bool
}

func (v NullableSdkAutomationModuleFile) Get() *SdkAutomationModuleFile {
	return v.value
}

func (v *NullableSdkAutomationModuleFile) Set(val *SdkAutomationModuleFile) {
	v.value = val
	v.isSet = true
}

func (v NullableSdkAutomationModuleFile) IsSet() bool {
	return v.isSet
}

func (v *NullableSdkAutomationModuleFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSdkAutomationModuleFile(val *SdkAutomationModuleFile) *NullableSdkAutomationModuleFile {
	return &NullableSdkAutomationModuleFile{value: val, isSet: true}
}

func (v NullableSdkAutomationModuleFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSdkAutomationModuleFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


