/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse{}

// V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse struct for V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse
type V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse struct {
	Job *SdkAutomationPlaybookJob `json:"job,omitempty"`
}

// NewV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse instantiates a new V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse() *V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse {
	this := V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponseWithDefaults instantiates a new V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponseWithDefaults() *V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse {
	this := V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse{}
	return &this
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) GetJob() SdkAutomationPlaybookJob {
	if o == nil || IsNil(o.Job) {
		var ret SdkAutomationPlaybookJob
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) GetJobOk() (*SdkAutomationPlaybookJob, bool) {
	if o == nil || IsNil(o.Job) {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) HasJob() bool {
	if o != nil && !IsNil(o.Job) {
		return true
	}

	return false
}

// SetJob gets a reference to the given SdkAutomationPlaybookJob and assigns it to the Job field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) SetJob(v SdkAutomationPlaybookJob) {
	o.Job = &v
}

func (o V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Job) {
		toSerialize["job"] = o.Job
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse struct {
	value *V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) Get() *V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) Set(val *V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse(val *V1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) *NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse {
	return &NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


