/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the SdkAutomationCatalogBundle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SdkAutomationCatalogBundle{}

// SdkAutomationCatalogBundle struct for SdkAutomationCatalogBundle
type SdkAutomationCatalogBundle struct {
	// Short description of the bundle
	Description *string `json:"description,omitempty"`
	// Stable catalog key (e.g. system_bundle); used as CreatePlaybookConfigRequest.bundle_key
	Key *string `json:"key,omitempty"`
	// Display name for the UI picklist
	Name *string `json:"name,omitempty"`
}

// NewSdkAutomationCatalogBundle instantiates a new SdkAutomationCatalogBundle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSdkAutomationCatalogBundle() *SdkAutomationCatalogBundle {
	this := SdkAutomationCatalogBundle{}
	return &this
}

// NewSdkAutomationCatalogBundleWithDefaults instantiates a new SdkAutomationCatalogBundle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSdkAutomationCatalogBundleWithDefaults() *SdkAutomationCatalogBundle {
	this := SdkAutomationCatalogBundle{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SdkAutomationCatalogBundle) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationCatalogBundle) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SdkAutomationCatalogBundle) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SdkAutomationCatalogBundle) SetDescription(v string) {
	o.Description = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *SdkAutomationCatalogBundle) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationCatalogBundle) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *SdkAutomationCatalogBundle) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *SdkAutomationCatalogBundle) SetKey(v string) {
	o.Key = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SdkAutomationCatalogBundle) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationCatalogBundle) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SdkAutomationCatalogBundle) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SdkAutomationCatalogBundle) SetName(v string) {
	o.Name = &v
}

func (o SdkAutomationCatalogBundle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SdkAutomationCatalogBundle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableSdkAutomationCatalogBundle struct {
	value *SdkAutomationCatalogBundle
	isSet bool
}

func (v NullableSdkAutomationCatalogBundle) Get() *SdkAutomationCatalogBundle {
	return v.value
}

func (v *NullableSdkAutomationCatalogBundle) Set(val *SdkAutomationCatalogBundle) {
	v.value = val
	v.isSet = true
}

func (v NullableSdkAutomationCatalogBundle) IsSet() bool {
	return v.isSet
}

func (v *NullableSdkAutomationCatalogBundle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSdkAutomationCatalogBundle(val *SdkAutomationCatalogBundle) *NullableSdkAutomationCatalogBundle {
	return &NullableSdkAutomationCatalogBundle{value: val, isSet: true}
}

func (v NullableSdkAutomationCatalogBundle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSdkAutomationCatalogBundle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


