/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V2MonitoringFecStatsGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2MonitoringFecStatsGetResponse{}

// V2MonitoringFecStatsGetResponse struct for V2MonitoringFecStatsGetResponse
type V2MonitoringFecStatsGetResponse struct {
	CurrentRepairLevel *float32 `json:"currentRepairLevel,omitempty"`
	EffectiveQoe *float32 `json:"effectiveQoe,omitempty"`
	RxRepairLevelHistogram *StatsmonV2FecRxRepairLevel `json:"rxRepairLevelHistogram,omitempty"`
	RxStats *StatsmonV2FecRxStats `json:"rxStats,omitempty"`
	TxRepairLevelHistogram *StatsmonV2FecTxRepairLevel `json:"txRepairLevelHistogram,omitempty"`
	TxStats *StatsmonV2FecTxStats `json:"txStats,omitempty"`
	UnrepairableRate *float32 `json:"unrepairableRate,omitempty"`
}

// NewV2MonitoringFecStatsGetResponse instantiates a new V2MonitoringFecStatsGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2MonitoringFecStatsGetResponse() *V2MonitoringFecStatsGetResponse {
	this := V2MonitoringFecStatsGetResponse{}
	return &this
}

// NewV2MonitoringFecStatsGetResponseWithDefaults instantiates a new V2MonitoringFecStatsGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2MonitoringFecStatsGetResponseWithDefaults() *V2MonitoringFecStatsGetResponse {
	this := V2MonitoringFecStatsGetResponse{}
	return &this
}

// GetCurrentRepairLevel returns the CurrentRepairLevel field value if set, zero value otherwise.
func (o *V2MonitoringFecStatsGetResponse) GetCurrentRepairLevel() float32 {
	if o == nil || IsNil(o.CurrentRepairLevel) {
		var ret float32
		return ret
	}
	return *o.CurrentRepairLevel
}

// GetCurrentRepairLevelOk returns a tuple with the CurrentRepairLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2MonitoringFecStatsGetResponse) GetCurrentRepairLevelOk() (*float32, bool) {
	if o == nil || IsNil(o.CurrentRepairLevel) {
		return nil, false
	}
	return o.CurrentRepairLevel, true
}

// HasCurrentRepairLevel returns a boolean if a field has been set.
func (o *V2MonitoringFecStatsGetResponse) HasCurrentRepairLevel() bool {
	if o != nil && !IsNil(o.CurrentRepairLevel) {
		return true
	}

	return false
}

// SetCurrentRepairLevel gets a reference to the given float32 and assigns it to the CurrentRepairLevel field.
func (o *V2MonitoringFecStatsGetResponse) SetCurrentRepairLevel(v float32) {
	o.CurrentRepairLevel = &v
}

// GetEffectiveQoe returns the EffectiveQoe field value if set, zero value otherwise.
func (o *V2MonitoringFecStatsGetResponse) GetEffectiveQoe() float32 {
	if o == nil || IsNil(o.EffectiveQoe) {
		var ret float32
		return ret
	}
	return *o.EffectiveQoe
}

// GetEffectiveQoeOk returns a tuple with the EffectiveQoe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2MonitoringFecStatsGetResponse) GetEffectiveQoeOk() (*float32, bool) {
	if o == nil || IsNil(o.EffectiveQoe) {
		return nil, false
	}
	return o.EffectiveQoe, true
}

// HasEffectiveQoe returns a boolean if a field has been set.
func (o *V2MonitoringFecStatsGetResponse) HasEffectiveQoe() bool {
	if o != nil && !IsNil(o.EffectiveQoe) {
		return true
	}

	return false
}

// SetEffectiveQoe gets a reference to the given float32 and assigns it to the EffectiveQoe field.
func (o *V2MonitoringFecStatsGetResponse) SetEffectiveQoe(v float32) {
	o.EffectiveQoe = &v
}

// GetRxRepairLevelHistogram returns the RxRepairLevelHistogram field value if set, zero value otherwise.
func (o *V2MonitoringFecStatsGetResponse) GetRxRepairLevelHistogram() StatsmonV2FecRxRepairLevel {
	if o == nil || IsNil(o.RxRepairLevelHistogram) {
		var ret StatsmonV2FecRxRepairLevel
		return ret
	}
	return *o.RxRepairLevelHistogram
}

// GetRxRepairLevelHistogramOk returns a tuple with the RxRepairLevelHistogram field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2MonitoringFecStatsGetResponse) GetRxRepairLevelHistogramOk() (*StatsmonV2FecRxRepairLevel, bool) {
	if o == nil || IsNil(o.RxRepairLevelHistogram) {
		return nil, false
	}
	return o.RxRepairLevelHistogram, true
}

// HasRxRepairLevelHistogram returns a boolean if a field has been set.
func (o *V2MonitoringFecStatsGetResponse) HasRxRepairLevelHistogram() bool {
	if o != nil && !IsNil(o.RxRepairLevelHistogram) {
		return true
	}

	return false
}

// SetRxRepairLevelHistogram gets a reference to the given StatsmonV2FecRxRepairLevel and assigns it to the RxRepairLevelHistogram field.
func (o *V2MonitoringFecStatsGetResponse) SetRxRepairLevelHistogram(v StatsmonV2FecRxRepairLevel) {
	o.RxRepairLevelHistogram = &v
}

// GetRxStats returns the RxStats field value if set, zero value otherwise.
func (o *V2MonitoringFecStatsGetResponse) GetRxStats() StatsmonV2FecRxStats {
	if o == nil || IsNil(o.RxStats) {
		var ret StatsmonV2FecRxStats
		return ret
	}
	return *o.RxStats
}

// GetRxStatsOk returns a tuple with the RxStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2MonitoringFecStatsGetResponse) GetRxStatsOk() (*StatsmonV2FecRxStats, bool) {
	if o == nil || IsNil(o.RxStats) {
		return nil, false
	}
	return o.RxStats, true
}

// HasRxStats returns a boolean if a field has been set.
func (o *V2MonitoringFecStatsGetResponse) HasRxStats() bool {
	if o != nil && !IsNil(o.RxStats) {
		return true
	}

	return false
}

// SetRxStats gets a reference to the given StatsmonV2FecRxStats and assigns it to the RxStats field.
func (o *V2MonitoringFecStatsGetResponse) SetRxStats(v StatsmonV2FecRxStats) {
	o.RxStats = &v
}

// GetTxRepairLevelHistogram returns the TxRepairLevelHistogram field value if set, zero value otherwise.
func (o *V2MonitoringFecStatsGetResponse) GetTxRepairLevelHistogram() StatsmonV2FecTxRepairLevel {
	if o == nil || IsNil(o.TxRepairLevelHistogram) {
		var ret StatsmonV2FecTxRepairLevel
		return ret
	}
	return *o.TxRepairLevelHistogram
}

// GetTxRepairLevelHistogramOk returns a tuple with the TxRepairLevelHistogram field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2MonitoringFecStatsGetResponse) GetTxRepairLevelHistogramOk() (*StatsmonV2FecTxRepairLevel, bool) {
	if o == nil || IsNil(o.TxRepairLevelHistogram) {
		return nil, false
	}
	return o.TxRepairLevelHistogram, true
}

// HasTxRepairLevelHistogram returns a boolean if a field has been set.
func (o *V2MonitoringFecStatsGetResponse) HasTxRepairLevelHistogram() bool {
	if o != nil && !IsNil(o.TxRepairLevelHistogram) {
		return true
	}

	return false
}

// SetTxRepairLevelHistogram gets a reference to the given StatsmonV2FecTxRepairLevel and assigns it to the TxRepairLevelHistogram field.
func (o *V2MonitoringFecStatsGetResponse) SetTxRepairLevelHistogram(v StatsmonV2FecTxRepairLevel) {
	o.TxRepairLevelHistogram = &v
}

// GetTxStats returns the TxStats field value if set, zero value otherwise.
func (o *V2MonitoringFecStatsGetResponse) GetTxStats() StatsmonV2FecTxStats {
	if o == nil || IsNil(o.TxStats) {
		var ret StatsmonV2FecTxStats
		return ret
	}
	return *o.TxStats
}

// GetTxStatsOk returns a tuple with the TxStats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2MonitoringFecStatsGetResponse) GetTxStatsOk() (*StatsmonV2FecTxStats, bool) {
	if o == nil || IsNil(o.TxStats) {
		return nil, false
	}
	return o.TxStats, true
}

// HasTxStats returns a boolean if a field has been set.
func (o *V2MonitoringFecStatsGetResponse) HasTxStats() bool {
	if o != nil && !IsNil(o.TxStats) {
		return true
	}

	return false
}

// SetTxStats gets a reference to the given StatsmonV2FecTxStats and assigns it to the TxStats field.
func (o *V2MonitoringFecStatsGetResponse) SetTxStats(v StatsmonV2FecTxStats) {
	o.TxStats = &v
}

// GetUnrepairableRate returns the UnrepairableRate field value if set, zero value otherwise.
func (o *V2MonitoringFecStatsGetResponse) GetUnrepairableRate() float32 {
	if o == nil || IsNil(o.UnrepairableRate) {
		var ret float32
		return ret
	}
	return *o.UnrepairableRate
}

// GetUnrepairableRateOk returns a tuple with the UnrepairableRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2MonitoringFecStatsGetResponse) GetUnrepairableRateOk() (*float32, bool) {
	if o == nil || IsNil(o.UnrepairableRate) {
		return nil, false
	}
	return o.UnrepairableRate, true
}

// HasUnrepairableRate returns a boolean if a field has been set.
func (o *V2MonitoringFecStatsGetResponse) HasUnrepairableRate() bool {
	if o != nil && !IsNil(o.UnrepairableRate) {
		return true
	}

	return false
}

// SetUnrepairableRate gets a reference to the given float32 and assigns it to the UnrepairableRate field.
func (o *V2MonitoringFecStatsGetResponse) SetUnrepairableRate(v float32) {
	o.UnrepairableRate = &v
}

func (o V2MonitoringFecStatsGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2MonitoringFecStatsGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrentRepairLevel) {
		toSerialize["currentRepairLevel"] = o.CurrentRepairLevel
	}
	if !IsNil(o.EffectiveQoe) {
		toSerialize["effectiveQoe"] = o.EffectiveQoe
	}
	if !IsNil(o.RxRepairLevelHistogram) {
		toSerialize["rxRepairLevelHistogram"] = o.RxRepairLevelHistogram
	}
	if !IsNil(o.RxStats) {
		toSerialize["rxStats"] = o.RxStats
	}
	if !IsNil(o.TxRepairLevelHistogram) {
		toSerialize["txRepairLevelHistogram"] = o.TxRepairLevelHistogram
	}
	if !IsNil(o.TxStats) {
		toSerialize["txStats"] = o.TxStats
	}
	if !IsNil(o.UnrepairableRate) {
		toSerialize["unrepairableRate"] = o.UnrepairableRate
	}
	return toSerialize, nil
}

type NullableV2MonitoringFecStatsGetResponse struct {
	value *V2MonitoringFecStatsGetResponse
	isSet bool
}

func (v NullableV2MonitoringFecStatsGetResponse) Get() *V2MonitoringFecStatsGetResponse {
	return v.value
}

func (v *NullableV2MonitoringFecStatsGetResponse) Set(val *V2MonitoringFecStatsGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2MonitoringFecStatsGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2MonitoringFecStatsGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2MonitoringFecStatsGetResponse(val *V2MonitoringFecStatsGetResponse) *NullableV2MonitoringFecStatsGetResponse {
	return &NullableV2MonitoringFecStatsGetResponse{value: val, isSet: true}
}

func (v NullableV2MonitoringFecStatsGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2MonitoringFecStatsGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


