/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookJobsJobIdGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookJobsJobIdGetResponse{}

// V1SdkAutomationPlaybookJobsJobIdGetResponse struct for V1SdkAutomationPlaybookJobsJobIdGetResponse
type V1SdkAutomationPlaybookJobsJobIdGetResponse struct {
	Job *SdkAutomationPlaybookJob `json:"job,omitempty"`
}

// NewV1SdkAutomationPlaybookJobsJobIdGetResponse instantiates a new V1SdkAutomationPlaybookJobsJobIdGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookJobsJobIdGetResponse() *V1SdkAutomationPlaybookJobsJobIdGetResponse {
	this := V1SdkAutomationPlaybookJobsJobIdGetResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookJobsJobIdGetResponseWithDefaults instantiates a new V1SdkAutomationPlaybookJobsJobIdGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookJobsJobIdGetResponseWithDefaults() *V1SdkAutomationPlaybookJobsJobIdGetResponse {
	this := V1SdkAutomationPlaybookJobsJobIdGetResponse{}
	return &this
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdGetResponse) GetJob() SdkAutomationPlaybookJob {
	if o == nil || IsNil(o.Job) {
		var ret SdkAutomationPlaybookJob
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdGetResponse) GetJobOk() (*SdkAutomationPlaybookJob, bool) {
	if o == nil || IsNil(o.Job) {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdGetResponse) HasJob() bool {
	if o != nil && !IsNil(o.Job) {
		return true
	}

	return false
}

// SetJob gets a reference to the given SdkAutomationPlaybookJob and assigns it to the Job field.
func (o *V1SdkAutomationPlaybookJobsJobIdGetResponse) SetJob(v SdkAutomationPlaybookJob) {
	o.Job = &v
}

func (o V1SdkAutomationPlaybookJobsJobIdGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookJobsJobIdGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Job) {
		toSerialize["job"] = o.Job
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookJobsJobIdGetResponse struct {
	value *V1SdkAutomationPlaybookJobsJobIdGetResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdGetResponse) Get() *V1SdkAutomationPlaybookJobsJobIdGetResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdGetResponse) Set(val *V1SdkAutomationPlaybookJobsJobIdGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookJobsJobIdGetResponse(val *V1SdkAutomationPlaybookJobsJobIdGetResponse) *NullableV1SdkAutomationPlaybookJobsJobIdGetResponse {
	return &NullableV1SdkAutomationPlaybookJobsJobIdGetResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


