/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest{}

// V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest struct for V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest
type V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest struct {
	// Deployment notes shown in the pending-executions UI
	Description *string `json:"description,omitempty"`
	// Required display name for the staged config
	Name *string `json:"name,omitempty"`
}

// NewV1SdkAutomationPlaybookConfigsConfigIdStagePutRequest instantiates a new V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookConfigsConfigIdStagePutRequest() *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest {
	this := V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest{}
	return &this
}

// NewV1SdkAutomationPlaybookConfigsConfigIdStagePutRequestWithDefaults instantiates a new V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookConfigsConfigIdStagePutRequestWithDefaults() *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest {
	this := V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) SetName(v string) {
	o.Name = &v
}

func (o V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutRequest struct {
	value *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) Get() *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) Set(val *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookConfigsConfigIdStagePutRequest(val *V1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) *NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutRequest {
	return &NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutRequest{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdStagePutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


