/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the SdkAutomationTemplateFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SdkAutomationTemplateFile{}

// SdkAutomationTemplateFile struct for SdkAutomationTemplateFile
type SdkAutomationTemplateFile struct {
	// File contents, verbatim from the collection
	Content *string `json:"content,omitempty"`
	// Suggested download name (e.g. sample_interface_config.yaml)
	Filename *string `json:"filename,omitempty"`
	// Catalog module key; empty for the bundle-level playbook not scoped to a slot
	ModuleKey *string `json:"moduleKey,omitempty"`
	// Path within the collection for provenance (e.g. playbooks/interface_management.yml)
	SourcePath *string `json:"sourcePath,omitempty"`
}

// NewSdkAutomationTemplateFile instantiates a new SdkAutomationTemplateFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSdkAutomationTemplateFile() *SdkAutomationTemplateFile {
	this := SdkAutomationTemplateFile{}
	return &this
}

// NewSdkAutomationTemplateFileWithDefaults instantiates a new SdkAutomationTemplateFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSdkAutomationTemplateFileWithDefaults() *SdkAutomationTemplateFile {
	this := SdkAutomationTemplateFile{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *SdkAutomationTemplateFile) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationTemplateFile) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *SdkAutomationTemplateFile) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *SdkAutomationTemplateFile) SetContent(v string) {
	o.Content = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *SdkAutomationTemplateFile) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationTemplateFile) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *SdkAutomationTemplateFile) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *SdkAutomationTemplateFile) SetFilename(v string) {
	o.Filename = &v
}

// GetModuleKey returns the ModuleKey field value if set, zero value otherwise.
func (o *SdkAutomationTemplateFile) GetModuleKey() string {
	if o == nil || IsNil(o.ModuleKey) {
		var ret string
		return ret
	}
	return *o.ModuleKey
}

// GetModuleKeyOk returns a tuple with the ModuleKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationTemplateFile) GetModuleKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ModuleKey) {
		return nil, false
	}
	return o.ModuleKey, true
}

// HasModuleKey returns a boolean if a field has been set.
func (o *SdkAutomationTemplateFile) HasModuleKey() bool {
	if o != nil && !IsNil(o.ModuleKey) {
		return true
	}

	return false
}

// SetModuleKey gets a reference to the given string and assigns it to the ModuleKey field.
func (o *SdkAutomationTemplateFile) SetModuleKey(v string) {
	o.ModuleKey = &v
}

// GetSourcePath returns the SourcePath field value if set, zero value otherwise.
func (o *SdkAutomationTemplateFile) GetSourcePath() string {
	if o == nil || IsNil(o.SourcePath) {
		var ret string
		return ret
	}
	return *o.SourcePath
}

// GetSourcePathOk returns a tuple with the SourcePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationTemplateFile) GetSourcePathOk() (*string, bool) {
	if o == nil || IsNil(o.SourcePath) {
		return nil, false
	}
	return o.SourcePath, true
}

// HasSourcePath returns a boolean if a field has been set.
func (o *SdkAutomationTemplateFile) HasSourcePath() bool {
	if o != nil && !IsNil(o.SourcePath) {
		return true
	}

	return false
}

// SetSourcePath gets a reference to the given string and assigns it to the SourcePath field.
func (o *SdkAutomationTemplateFile) SetSourcePath(v string) {
	o.SourcePath = &v
}

func (o SdkAutomationTemplateFile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SdkAutomationTemplateFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.ModuleKey) {
		toSerialize["moduleKey"] = o.ModuleKey
	}
	if !IsNil(o.SourcePath) {
		toSerialize["sourcePath"] = o.SourcePath
	}
	return toSerialize, nil
}

type NullableSdkAutomationTemplateFile struct {
	value *SdkAutomationTemplateFile
	isSet bool
}

func (v NullableSdkAutomationTemplateFile) Get() *SdkAutomationTemplateFile {
	return v.value
}

func (v *NullableSdkAutomationTemplateFile) Set(val *SdkAutomationTemplateFile) {
	v.value = val
	v.isSet = true
}

func (v NullableSdkAutomationTemplateFile) IsSet() bool {
	return v.isSet
}

func (v *NullableSdkAutomationTemplateFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSdkAutomationTemplateFile(val *SdkAutomationTemplateFile) *NullableSdkAutomationTemplateFile {
	return &NullableSdkAutomationTemplateFile{value: val, isSet: true}
}

func (v NullableSdkAutomationTemplateFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSdkAutomationTemplateFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


