/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookConfigsConfigIdGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookConfigsConfigIdGetResponse{}

// V1SdkAutomationPlaybookConfigsConfigIdGetResponse struct for V1SdkAutomationPlaybookConfigsConfigIdGetResponse
type V1SdkAutomationPlaybookConfigsConfigIdGetResponse struct {
	Config *SdkAutomationPlaybookConfig `json:"config,omitempty"`
}

// NewV1SdkAutomationPlaybookConfigsConfigIdGetResponse instantiates a new V1SdkAutomationPlaybookConfigsConfigIdGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookConfigsConfigIdGetResponse() *V1SdkAutomationPlaybookConfigsConfigIdGetResponse {
	this := V1SdkAutomationPlaybookConfigsConfigIdGetResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookConfigsConfigIdGetResponseWithDefaults instantiates a new V1SdkAutomationPlaybookConfigsConfigIdGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookConfigsConfigIdGetResponseWithDefaults() *V1SdkAutomationPlaybookConfigsConfigIdGetResponse {
	this := V1SdkAutomationPlaybookConfigsConfigIdGetResponse{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdGetResponse) GetConfig() SdkAutomationPlaybookConfig {
	if o == nil || IsNil(o.Config) {
		var ret SdkAutomationPlaybookConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdGetResponse) GetConfigOk() (*SdkAutomationPlaybookConfig, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdGetResponse) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given SdkAutomationPlaybookConfig and assigns it to the Config field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdGetResponse) SetConfig(v SdkAutomationPlaybookConfig) {
	o.Config = &v
}

func (o V1SdkAutomationPlaybookConfigsConfigIdGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookConfigsConfigIdGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookConfigsConfigIdGetResponse struct {
	value *V1SdkAutomationPlaybookConfigsConfigIdGetResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdGetResponse) Get() *V1SdkAutomationPlaybookConfigsConfigIdGetResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdGetResponse) Set(val *V1SdkAutomationPlaybookConfigsConfigIdGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookConfigsConfigIdGetResponse(val *V1SdkAutomationPlaybookConfigsConfigIdGetResponse) *NullableV1SdkAutomationPlaybookConfigsConfigIdGetResponse {
	return &NullableV1SdkAutomationPlaybookConfigsConfigIdGetResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


