/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the SdkAutomationPlaybookConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SdkAutomationPlaybookConfig{}

// SdkAutomationPlaybookConfig struct for SdkAutomationPlaybookConfig
type SdkAutomationPlaybookConfig struct {
	// Catalog key from playbook_catalog_playbook (e.g. system_bundle)
	BundleKey *string `json:"bundleKey,omitempty"`
	// Config id
	ConfigId *string `json:"configId,omitempty"`
	// IAM user id of the config creator; UI resolves the display name
	CreatedByUserId *string `json:"createdByUserId,omitempty"`
	// Description / deployment notes
	Description *string `json:"description,omitempty"`
	Files []SdkAutomationModuleFile `json:"files,omitempty"`
	// Display name
	Name *string `json:"name,omitempty"`
	// Config lifecycle status (draft / staged / paused)
	Status *string `json:"status,omitempty"`
}

// NewSdkAutomationPlaybookConfig instantiates a new SdkAutomationPlaybookConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSdkAutomationPlaybookConfig() *SdkAutomationPlaybookConfig {
	this := SdkAutomationPlaybookConfig{}
	return &this
}

// NewSdkAutomationPlaybookConfigWithDefaults instantiates a new SdkAutomationPlaybookConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSdkAutomationPlaybookConfigWithDefaults() *SdkAutomationPlaybookConfig {
	this := SdkAutomationPlaybookConfig{}
	return &this
}

// GetBundleKey returns the BundleKey field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfig) GetBundleKey() string {
	if o == nil || IsNil(o.BundleKey) {
		var ret string
		return ret
	}
	return *o.BundleKey
}

// GetBundleKeyOk returns a tuple with the BundleKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfig) GetBundleKeyOk() (*string, bool) {
	if o == nil || IsNil(o.BundleKey) {
		return nil, false
	}
	return o.BundleKey, true
}

// HasBundleKey returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfig) HasBundleKey() bool {
	if o != nil && !IsNil(o.BundleKey) {
		return true
	}

	return false
}

// SetBundleKey gets a reference to the given string and assigns it to the BundleKey field.
func (o *SdkAutomationPlaybookConfig) SetBundleKey(v string) {
	o.BundleKey = &v
}

// GetConfigId returns the ConfigId field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfig) GetConfigId() string {
	if o == nil || IsNil(o.ConfigId) {
		var ret string
		return ret
	}
	return *o.ConfigId
}

// GetConfigIdOk returns a tuple with the ConfigId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfig) GetConfigIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConfigId) {
		return nil, false
	}
	return o.ConfigId, true
}

// HasConfigId returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfig) HasConfigId() bool {
	if o != nil && !IsNil(o.ConfigId) {
		return true
	}

	return false
}

// SetConfigId gets a reference to the given string and assigns it to the ConfigId field.
func (o *SdkAutomationPlaybookConfig) SetConfigId(v string) {
	o.ConfigId = &v
}

// GetCreatedByUserId returns the CreatedByUserId field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfig) GetCreatedByUserId() string {
	if o == nil || IsNil(o.CreatedByUserId) {
		var ret string
		return ret
	}
	return *o.CreatedByUserId
}

// GetCreatedByUserIdOk returns a tuple with the CreatedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfig) GetCreatedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByUserId) {
		return nil, false
	}
	return o.CreatedByUserId, true
}

// HasCreatedByUserId returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfig) HasCreatedByUserId() bool {
	if o != nil && !IsNil(o.CreatedByUserId) {
		return true
	}

	return false
}

// SetCreatedByUserId gets a reference to the given string and assigns it to the CreatedByUserId field.
func (o *SdkAutomationPlaybookConfig) SetCreatedByUserId(v string) {
	o.CreatedByUserId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfig) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfig) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfig) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SdkAutomationPlaybookConfig) SetDescription(v string) {
	o.Description = &v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfig) GetFiles() []SdkAutomationModuleFile {
	if o == nil || IsNil(o.Files) {
		var ret []SdkAutomationModuleFile
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfig) GetFilesOk() ([]SdkAutomationModuleFile, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfig) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []SdkAutomationModuleFile and assigns it to the Files field.
func (o *SdkAutomationPlaybookConfig) SetFiles(v []SdkAutomationModuleFile) {
	o.Files = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfig) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfig) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfig) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SdkAutomationPlaybookConfig) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookConfig) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookConfig) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookConfig) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SdkAutomationPlaybookConfig) SetStatus(v string) {
	o.Status = &v
}

func (o SdkAutomationPlaybookConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SdkAutomationPlaybookConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BundleKey) {
		toSerialize["bundleKey"] = o.BundleKey
	}
	if !IsNil(o.ConfigId) {
		toSerialize["configId"] = o.ConfigId
	}
	if !IsNil(o.CreatedByUserId) {
		toSerialize["createdByUserId"] = o.CreatedByUserId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableSdkAutomationPlaybookConfig struct {
	value *SdkAutomationPlaybookConfig
	isSet bool
}

func (v NullableSdkAutomationPlaybookConfig) Get() *SdkAutomationPlaybookConfig {
	return v.value
}

func (v *NullableSdkAutomationPlaybookConfig) Set(val *SdkAutomationPlaybookConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableSdkAutomationPlaybookConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableSdkAutomationPlaybookConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSdkAutomationPlaybookConfig(val *SdkAutomationPlaybookConfig) *NullableSdkAutomationPlaybookConfig {
	return &NullableSdkAutomationPlaybookConfig{value: val, isSet: true}
}

func (v NullableSdkAutomationPlaybookConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSdkAutomationPlaybookConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


