/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookJobsJobIdLogsGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookJobsJobIdLogsGetResponse{}

// V1SdkAutomationPlaybookJobsJobIdLogsGetResponse struct for V1SdkAutomationPlaybookJobsJobIdLogsGetResponse
type V1SdkAutomationPlaybookJobsJobIdLogsGetResponse struct {
	Lines []string `json:"lines,omitempty"`
}

// NewV1SdkAutomationPlaybookJobsJobIdLogsGetResponse instantiates a new V1SdkAutomationPlaybookJobsJobIdLogsGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookJobsJobIdLogsGetResponse() *V1SdkAutomationPlaybookJobsJobIdLogsGetResponse {
	this := V1SdkAutomationPlaybookJobsJobIdLogsGetResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookJobsJobIdLogsGetResponseWithDefaults instantiates a new V1SdkAutomationPlaybookJobsJobIdLogsGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookJobsJobIdLogsGetResponseWithDefaults() *V1SdkAutomationPlaybookJobsJobIdLogsGetResponse {
	this := V1SdkAutomationPlaybookJobsJobIdLogsGetResponse{}
	return &this
}

// GetLines returns the Lines field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdLogsGetResponse) GetLines() []string {
	if o == nil || IsNil(o.Lines) {
		var ret []string
		return ret
	}
	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdLogsGetResponse) GetLinesOk() ([]string, bool) {
	if o == nil || IsNil(o.Lines) {
		return nil, false
	}
	return o.Lines, true
}

// HasLines returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdLogsGetResponse) HasLines() bool {
	if o != nil && !IsNil(o.Lines) {
		return true
	}

	return false
}

// SetLines gets a reference to the given []string and assigns it to the Lines field.
func (o *V1SdkAutomationPlaybookJobsJobIdLogsGetResponse) SetLines(v []string) {
	o.Lines = v
}

func (o V1SdkAutomationPlaybookJobsJobIdLogsGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookJobsJobIdLogsGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Lines) {
		toSerialize["lines"] = o.Lines
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookJobsJobIdLogsGetResponse struct {
	value *V1SdkAutomationPlaybookJobsJobIdLogsGetResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdLogsGetResponse) Get() *V1SdkAutomationPlaybookJobsJobIdLogsGetResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdLogsGetResponse) Set(val *V1SdkAutomationPlaybookJobsJobIdLogsGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdLogsGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdLogsGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookJobsJobIdLogsGetResponse(val *V1SdkAutomationPlaybookJobsJobIdLogsGetResponse) *NullableV1SdkAutomationPlaybookJobsJobIdLogsGetResponse {
	return &NullableV1SdkAutomationPlaybookJobsJobIdLogsGetResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdLogsGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdLogsGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


