/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the StatsmonV2FecTxStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsmonV2FecTxStats{}

// StatsmonV2FecTxStats struct for StatsmonV2FecTxStats
type StatsmonV2FecTxStats struct {
	ProtectedPackets *int64 `json:"protectedPackets,omitempty"`
	RepairLevel *float32 `json:"repairLevel,omitempty"`
	SentRepairPackets *int64 `json:"sentRepairPackets,omitempty"`
	UnprotectedPackets *int64 `json:"unprotectedPackets,omitempty"`
}

// NewStatsmonV2FecTxStats instantiates a new StatsmonV2FecTxStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsmonV2FecTxStats() *StatsmonV2FecTxStats {
	this := StatsmonV2FecTxStats{}
	return &this
}

// NewStatsmonV2FecTxStatsWithDefaults instantiates a new StatsmonV2FecTxStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsmonV2FecTxStatsWithDefaults() *StatsmonV2FecTxStats {
	this := StatsmonV2FecTxStats{}
	return &this
}

// GetProtectedPackets returns the ProtectedPackets field value if set, zero value otherwise.
func (o *StatsmonV2FecTxStats) GetProtectedPackets() int64 {
	if o == nil || IsNil(o.ProtectedPackets) {
		var ret int64
		return ret
	}
	return *o.ProtectedPackets
}

// GetProtectedPacketsOk returns a tuple with the ProtectedPackets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2FecTxStats) GetProtectedPacketsOk() (*int64, bool) {
	if o == nil || IsNil(o.ProtectedPackets) {
		return nil, false
	}
	return o.ProtectedPackets, true
}

// HasProtectedPackets returns a boolean if a field has been set.
func (o *StatsmonV2FecTxStats) HasProtectedPackets() bool {
	if o != nil && !IsNil(o.ProtectedPackets) {
		return true
	}

	return false
}

// SetProtectedPackets gets a reference to the given int64 and assigns it to the ProtectedPackets field.
func (o *StatsmonV2FecTxStats) SetProtectedPackets(v int64) {
	o.ProtectedPackets = &v
}

// GetRepairLevel returns the RepairLevel field value if set, zero value otherwise.
func (o *StatsmonV2FecTxStats) GetRepairLevel() float32 {
	if o == nil || IsNil(o.RepairLevel) {
		var ret float32
		return ret
	}
	return *o.RepairLevel
}

// GetRepairLevelOk returns a tuple with the RepairLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2FecTxStats) GetRepairLevelOk() (*float32, bool) {
	if o == nil || IsNil(o.RepairLevel) {
		return nil, false
	}
	return o.RepairLevel, true
}

// HasRepairLevel returns a boolean if a field has been set.
func (o *StatsmonV2FecTxStats) HasRepairLevel() bool {
	if o != nil && !IsNil(o.RepairLevel) {
		return true
	}

	return false
}

// SetRepairLevel gets a reference to the given float32 and assigns it to the RepairLevel field.
func (o *StatsmonV2FecTxStats) SetRepairLevel(v float32) {
	o.RepairLevel = &v
}

// GetSentRepairPackets returns the SentRepairPackets field value if set, zero value otherwise.
func (o *StatsmonV2FecTxStats) GetSentRepairPackets() int64 {
	if o == nil || IsNil(o.SentRepairPackets) {
		var ret int64
		return ret
	}
	return *o.SentRepairPackets
}

// GetSentRepairPacketsOk returns a tuple with the SentRepairPackets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2FecTxStats) GetSentRepairPacketsOk() (*int64, bool) {
	if o == nil || IsNil(o.SentRepairPackets) {
		return nil, false
	}
	return o.SentRepairPackets, true
}

// HasSentRepairPackets returns a boolean if a field has been set.
func (o *StatsmonV2FecTxStats) HasSentRepairPackets() bool {
	if o != nil && !IsNil(o.SentRepairPackets) {
		return true
	}

	return false
}

// SetSentRepairPackets gets a reference to the given int64 and assigns it to the SentRepairPackets field.
func (o *StatsmonV2FecTxStats) SetSentRepairPackets(v int64) {
	o.SentRepairPackets = &v
}

// GetUnprotectedPackets returns the UnprotectedPackets field value if set, zero value otherwise.
func (o *StatsmonV2FecTxStats) GetUnprotectedPackets() int64 {
	if o == nil || IsNil(o.UnprotectedPackets) {
		var ret int64
		return ret
	}
	return *o.UnprotectedPackets
}

// GetUnprotectedPacketsOk returns a tuple with the UnprotectedPackets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2FecTxStats) GetUnprotectedPacketsOk() (*int64, bool) {
	if o == nil || IsNil(o.UnprotectedPackets) {
		return nil, false
	}
	return o.UnprotectedPackets, true
}

// HasUnprotectedPackets returns a boolean if a field has been set.
func (o *StatsmonV2FecTxStats) HasUnprotectedPackets() bool {
	if o != nil && !IsNil(o.UnprotectedPackets) {
		return true
	}

	return false
}

// SetUnprotectedPackets gets a reference to the given int64 and assigns it to the UnprotectedPackets field.
func (o *StatsmonV2FecTxStats) SetUnprotectedPackets(v int64) {
	o.UnprotectedPackets = &v
}

func (o StatsmonV2FecTxStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsmonV2FecTxStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProtectedPackets) {
		toSerialize["protectedPackets"] = o.ProtectedPackets
	}
	if !IsNil(o.RepairLevel) {
		toSerialize["repairLevel"] = o.RepairLevel
	}
	if !IsNil(o.SentRepairPackets) {
		toSerialize["sentRepairPackets"] = o.SentRepairPackets
	}
	if !IsNil(o.UnprotectedPackets) {
		toSerialize["unprotectedPackets"] = o.UnprotectedPackets
	}
	return toSerialize, nil
}

type NullableStatsmonV2FecTxStats struct {
	value *StatsmonV2FecTxStats
	isSet bool
}

func (v NullableStatsmonV2FecTxStats) Get() *StatsmonV2FecTxStats {
	return v.value
}

func (v *NullableStatsmonV2FecTxStats) Set(val *StatsmonV2FecTxStats) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsmonV2FecTxStats) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsmonV2FecTxStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsmonV2FecTxStats(val *StatsmonV2FecTxStats) *NullableStatsmonV2FecTxStats {
	return &NullableStatsmonV2FecTxStats{value: val, isSet: true}
}

func (v NullableStatsmonV2FecTxStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsmonV2FecTxStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


