/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1EdgesSummaryPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1EdgesSummaryPostRequest{}

// V1EdgesSummaryPostRequest struct for V1EdgesSummaryPostRequest
type V1EdgesSummaryPostRequest struct {
	Filter *V1EdgesSummaryPostRequestFilter `json:"filter,omitempty"`
	// Include devices excluded from Graphiant API lists. Ignored for non-Graphiant callers. Default false.
	ShowExcluded *bool `json:"showExcluded,omitempty"`
}

// NewV1EdgesSummaryPostRequest instantiates a new V1EdgesSummaryPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1EdgesSummaryPostRequest() *V1EdgesSummaryPostRequest {
	this := V1EdgesSummaryPostRequest{}
	return &this
}

// NewV1EdgesSummaryPostRequestWithDefaults instantiates a new V1EdgesSummaryPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1EdgesSummaryPostRequestWithDefaults() *V1EdgesSummaryPostRequest {
	this := V1EdgesSummaryPostRequest{}
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *V1EdgesSummaryPostRequest) GetFilter() V1EdgesSummaryPostRequestFilter {
	if o == nil || IsNil(o.Filter) {
		var ret V1EdgesSummaryPostRequestFilter
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EdgesSummaryPostRequest) GetFilterOk() (*V1EdgesSummaryPostRequestFilter, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *V1EdgesSummaryPostRequest) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given V1EdgesSummaryPostRequestFilter and assigns it to the Filter field.
func (o *V1EdgesSummaryPostRequest) SetFilter(v V1EdgesSummaryPostRequestFilter) {
	o.Filter = &v
}

// GetShowExcluded returns the ShowExcluded field value if set, zero value otherwise.
func (o *V1EdgesSummaryPostRequest) GetShowExcluded() bool {
	if o == nil || IsNil(o.ShowExcluded) {
		var ret bool
		return ret
	}
	return *o.ShowExcluded
}

// GetShowExcludedOk returns a tuple with the ShowExcluded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EdgesSummaryPostRequest) GetShowExcludedOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowExcluded) {
		return nil, false
	}
	return o.ShowExcluded, true
}

// HasShowExcluded returns a boolean if a field has been set.
func (o *V1EdgesSummaryPostRequest) HasShowExcluded() bool {
	if o != nil && !IsNil(o.ShowExcluded) {
		return true
	}

	return false
}

// SetShowExcluded gets a reference to the given bool and assigns it to the ShowExcluded field.
func (o *V1EdgesSummaryPostRequest) SetShowExcluded(v bool) {
	o.ShowExcluded = &v
}

func (o V1EdgesSummaryPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1EdgesSummaryPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	if !IsNil(o.ShowExcluded) {
		toSerialize["showExcluded"] = o.ShowExcluded
	}
	return toSerialize, nil
}

type NullableV1EdgesSummaryPostRequest struct {
	value *V1EdgesSummaryPostRequest
	isSet bool
}

func (v NullableV1EdgesSummaryPostRequest) Get() *V1EdgesSummaryPostRequest {
	return v.value
}

func (v *NullableV1EdgesSummaryPostRequest) Set(val *V1EdgesSummaryPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1EdgesSummaryPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1EdgesSummaryPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1EdgesSummaryPostRequest(val *V1EdgesSummaryPostRequest) *NullableV1EdgesSummaryPostRequest {
	return &NullableV1EdgesSummaryPostRequest{value: val, isSet: true}
}

func (v NullableV1EdgesSummaryPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1EdgesSummaryPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


