/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookBundlesGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookBundlesGetResponse{}

// V1SdkAutomationPlaybookBundlesGetResponse struct for V1SdkAutomationPlaybookBundlesGetResponse
type V1SdkAutomationPlaybookBundlesGetResponse struct {
	Bundles []SdkAutomationCatalogBundle `json:"bundles,omitempty"`
}

// NewV1SdkAutomationPlaybookBundlesGetResponse instantiates a new V1SdkAutomationPlaybookBundlesGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookBundlesGetResponse() *V1SdkAutomationPlaybookBundlesGetResponse {
	this := V1SdkAutomationPlaybookBundlesGetResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookBundlesGetResponseWithDefaults instantiates a new V1SdkAutomationPlaybookBundlesGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookBundlesGetResponseWithDefaults() *V1SdkAutomationPlaybookBundlesGetResponse {
	this := V1SdkAutomationPlaybookBundlesGetResponse{}
	return &this
}

// GetBundles returns the Bundles field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookBundlesGetResponse) GetBundles() []SdkAutomationCatalogBundle {
	if o == nil || IsNil(o.Bundles) {
		var ret []SdkAutomationCatalogBundle
		return ret
	}
	return o.Bundles
}

// GetBundlesOk returns a tuple with the Bundles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookBundlesGetResponse) GetBundlesOk() ([]SdkAutomationCatalogBundle, bool) {
	if o == nil || IsNil(o.Bundles) {
		return nil, false
	}
	return o.Bundles, true
}

// HasBundles returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookBundlesGetResponse) HasBundles() bool {
	if o != nil && !IsNil(o.Bundles) {
		return true
	}

	return false
}

// SetBundles gets a reference to the given []SdkAutomationCatalogBundle and assigns it to the Bundles field.
func (o *V1SdkAutomationPlaybookBundlesGetResponse) SetBundles(v []SdkAutomationCatalogBundle) {
	o.Bundles = v
}

func (o V1SdkAutomationPlaybookBundlesGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookBundlesGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bundles) {
		toSerialize["bundles"] = o.Bundles
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookBundlesGetResponse struct {
	value *V1SdkAutomationPlaybookBundlesGetResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookBundlesGetResponse) Get() *V1SdkAutomationPlaybookBundlesGetResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookBundlesGetResponse) Set(val *V1SdkAutomationPlaybookBundlesGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookBundlesGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookBundlesGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookBundlesGetResponse(val *V1SdkAutomationPlaybookBundlesGetResponse) *NullableV1SdkAutomationPlaybookBundlesGetResponse {
	return &NullableV1SdkAutomationPlaybookBundlesGetResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookBundlesGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookBundlesGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


