/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookJobsJobIdRunPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookJobsJobIdRunPostRequest{}

// V1SdkAutomationPlaybookJobsJobIdRunPostRequest struct for V1SdkAutomationPlaybookJobsJobIdRunPostRequest
type V1SdkAutomationPlaybookJobsJobIdRunPostRequest struct {
	// When true, skip dry-run and gate and deploy directly
	SkipDryRun *bool `json:"skipDryRun,omitempty"`
	// When true, request ansible -vvv for the new run
	VerboseLogs *bool `json:"verboseLogs,omitempty"`
}

// NewV1SdkAutomationPlaybookJobsJobIdRunPostRequest instantiates a new V1SdkAutomationPlaybookJobsJobIdRunPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookJobsJobIdRunPostRequest() *V1SdkAutomationPlaybookJobsJobIdRunPostRequest {
	this := V1SdkAutomationPlaybookJobsJobIdRunPostRequest{}
	return &this
}

// NewV1SdkAutomationPlaybookJobsJobIdRunPostRequestWithDefaults instantiates a new V1SdkAutomationPlaybookJobsJobIdRunPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookJobsJobIdRunPostRequestWithDefaults() *V1SdkAutomationPlaybookJobsJobIdRunPostRequest {
	this := V1SdkAutomationPlaybookJobsJobIdRunPostRequest{}
	return &this
}

// GetSkipDryRun returns the SkipDryRun field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostRequest) GetSkipDryRun() bool {
	if o == nil || IsNil(o.SkipDryRun) {
		var ret bool
		return ret
	}
	return *o.SkipDryRun
}

// GetSkipDryRunOk returns a tuple with the SkipDryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostRequest) GetSkipDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipDryRun) {
		return nil, false
	}
	return o.SkipDryRun, true
}

// HasSkipDryRun returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostRequest) HasSkipDryRun() bool {
	if o != nil && !IsNil(o.SkipDryRun) {
		return true
	}

	return false
}

// SetSkipDryRun gets a reference to the given bool and assigns it to the SkipDryRun field.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostRequest) SetSkipDryRun(v bool) {
	o.SkipDryRun = &v
}

// GetVerboseLogs returns the VerboseLogs field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostRequest) GetVerboseLogs() bool {
	if o == nil || IsNil(o.VerboseLogs) {
		var ret bool
		return ret
	}
	return *o.VerboseLogs
}

// GetVerboseLogsOk returns a tuple with the VerboseLogs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostRequest) GetVerboseLogsOk() (*bool, bool) {
	if o == nil || IsNil(o.VerboseLogs) {
		return nil, false
	}
	return o.VerboseLogs, true
}

// HasVerboseLogs returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostRequest) HasVerboseLogs() bool {
	if o != nil && !IsNil(o.VerboseLogs) {
		return true
	}

	return false
}

// SetVerboseLogs gets a reference to the given bool and assigns it to the VerboseLogs field.
func (o *V1SdkAutomationPlaybookJobsJobIdRunPostRequest) SetVerboseLogs(v bool) {
	o.VerboseLogs = &v
}

func (o V1SdkAutomationPlaybookJobsJobIdRunPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookJobsJobIdRunPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SkipDryRun) {
		toSerialize["skipDryRun"] = o.SkipDryRun
	}
	if !IsNil(o.VerboseLogs) {
		toSerialize["verboseLogs"] = o.VerboseLogs
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookJobsJobIdRunPostRequest struct {
	value *V1SdkAutomationPlaybookJobsJobIdRunPostRequest
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdRunPostRequest) Get() *V1SdkAutomationPlaybookJobsJobIdRunPostRequest {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdRunPostRequest) Set(val *V1SdkAutomationPlaybookJobsJobIdRunPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdRunPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdRunPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookJobsJobIdRunPostRequest(val *V1SdkAutomationPlaybookJobsJobIdRunPostRequest) *NullableV1SdkAutomationPlaybookJobsJobIdRunPostRequest {
	return &NullableV1SdkAutomationPlaybookJobsJobIdRunPostRequest{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdRunPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdRunPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


