/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookJobsGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookJobsGetResponse{}

// V1SdkAutomationPlaybookJobsGetResponse struct for V1SdkAutomationPlaybookJobsGetResponse
type V1SdkAutomationPlaybookJobsGetResponse struct {
	Jobs []SdkAutomationPlaybookJob `json:"jobs,omitempty"`
	PageInfo *CommonPageInfo `json:"pageInfo,omitempty"`
}

// NewV1SdkAutomationPlaybookJobsGetResponse instantiates a new V1SdkAutomationPlaybookJobsGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookJobsGetResponse() *V1SdkAutomationPlaybookJobsGetResponse {
	this := V1SdkAutomationPlaybookJobsGetResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookJobsGetResponseWithDefaults instantiates a new V1SdkAutomationPlaybookJobsGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookJobsGetResponseWithDefaults() *V1SdkAutomationPlaybookJobsGetResponse {
	this := V1SdkAutomationPlaybookJobsGetResponse{}
	return &this
}

// GetJobs returns the Jobs field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsGetResponse) GetJobs() []SdkAutomationPlaybookJob {
	if o == nil || IsNil(o.Jobs) {
		var ret []SdkAutomationPlaybookJob
		return ret
	}
	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsGetResponse) GetJobsOk() ([]SdkAutomationPlaybookJob, bool) {
	if o == nil || IsNil(o.Jobs) {
		return nil, false
	}
	return o.Jobs, true
}

// HasJobs returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsGetResponse) HasJobs() bool {
	if o != nil && !IsNil(o.Jobs) {
		return true
	}

	return false
}

// SetJobs gets a reference to the given []SdkAutomationPlaybookJob and assigns it to the Jobs field.
func (o *V1SdkAutomationPlaybookJobsGetResponse) SetJobs(v []SdkAutomationPlaybookJob) {
	o.Jobs = v
}

// GetPageInfo returns the PageInfo field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsGetResponse) GetPageInfo() CommonPageInfo {
	if o == nil || IsNil(o.PageInfo) {
		var ret CommonPageInfo
		return ret
	}
	return *o.PageInfo
}

// GetPageInfoOk returns a tuple with the PageInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsGetResponse) GetPageInfoOk() (*CommonPageInfo, bool) {
	if o == nil || IsNil(o.PageInfo) {
		return nil, false
	}
	return o.PageInfo, true
}

// HasPageInfo returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsGetResponse) HasPageInfo() bool {
	if o != nil && !IsNil(o.PageInfo) {
		return true
	}

	return false
}

// SetPageInfo gets a reference to the given CommonPageInfo and assigns it to the PageInfo field.
func (o *V1SdkAutomationPlaybookJobsGetResponse) SetPageInfo(v CommonPageInfo) {
	o.PageInfo = &v
}

func (o V1SdkAutomationPlaybookJobsGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookJobsGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Jobs) {
		toSerialize["jobs"] = o.Jobs
	}
	if !IsNil(o.PageInfo) {
		toSerialize["pageInfo"] = o.PageInfo
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookJobsGetResponse struct {
	value *V1SdkAutomationPlaybookJobsGetResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookJobsGetResponse) Get() *V1SdkAutomationPlaybookJobsGetResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookJobsGetResponse) Set(val *V1SdkAutomationPlaybookJobsGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookJobsGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookJobsGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookJobsGetResponse(val *V1SdkAutomationPlaybookJobsGetResponse) *NullableV1SdkAutomationPlaybookJobsGetResponse {
	return &NullableV1SdkAutomationPlaybookJobsGetResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookJobsGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookJobsGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


