/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the SdkAutomationValidationError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SdkAutomationValidationError{}

// SdkAutomationValidationError struct for SdkAutomationValidationError
type SdkAutomationValidationError struct {
	// Human-readable validation error detail
	Message *string `json:"message,omitempty"`
	// Catalog module key when the error is scoped to a module; unset otherwise
	ModuleKey *string `json:"moduleKey,omitempty"`
	// Error category (syntax or schema)
	Type *string `json:"type,omitempty"`
}

// NewSdkAutomationValidationError instantiates a new SdkAutomationValidationError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSdkAutomationValidationError() *SdkAutomationValidationError {
	this := SdkAutomationValidationError{}
	return &this
}

// NewSdkAutomationValidationErrorWithDefaults instantiates a new SdkAutomationValidationError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSdkAutomationValidationErrorWithDefaults() *SdkAutomationValidationError {
	this := SdkAutomationValidationError{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SdkAutomationValidationError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationValidationError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SdkAutomationValidationError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SdkAutomationValidationError) SetMessage(v string) {
	o.Message = &v
}

// GetModuleKey returns the ModuleKey field value if set, zero value otherwise.
func (o *SdkAutomationValidationError) GetModuleKey() string {
	if o == nil || IsNil(o.ModuleKey) {
		var ret string
		return ret
	}
	return *o.ModuleKey
}

// GetModuleKeyOk returns a tuple with the ModuleKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationValidationError) GetModuleKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ModuleKey) {
		return nil, false
	}
	return o.ModuleKey, true
}

// HasModuleKey returns a boolean if a field has been set.
func (o *SdkAutomationValidationError) HasModuleKey() bool {
	if o != nil && !IsNil(o.ModuleKey) {
		return true
	}

	return false
}

// SetModuleKey gets a reference to the given string and assigns it to the ModuleKey field.
func (o *SdkAutomationValidationError) SetModuleKey(v string) {
	o.ModuleKey = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SdkAutomationValidationError) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationValidationError) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SdkAutomationValidationError) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SdkAutomationValidationError) SetType(v string) {
	o.Type = &v
}

func (o SdkAutomationValidationError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SdkAutomationValidationError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ModuleKey) {
		toSerialize["moduleKey"] = o.ModuleKey
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableSdkAutomationValidationError struct {
	value *SdkAutomationValidationError
	isSet bool
}

func (v NullableSdkAutomationValidationError) Get() *SdkAutomationValidationError {
	return v.value
}

func (v *NullableSdkAutomationValidationError) Set(val *SdkAutomationValidationError) {
	v.value = val
	v.isSet = true
}

func (v NullableSdkAutomationValidationError) IsSet() bool {
	return v.isSet
}

func (v *NullableSdkAutomationValidationError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSdkAutomationValidationError(val *SdkAutomationValidationError) *NullableSdkAutomationValidationError {
	return &NullableSdkAutomationValidationError{value: val, isSet: true}
}

func (v NullableSdkAutomationValidationError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSdkAutomationValidationError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


