/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookConfigsPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookConfigsPostResponse{}

// V1SdkAutomationPlaybookConfigsPostResponse struct for V1SdkAutomationPlaybookConfigsPostResponse
type V1SdkAutomationPlaybookConfigsPostResponse struct {
	// Created config id when validation succeeds and validate_only is false; empty otherwise
	ConfigId *string `json:"configId,omitempty"`
	Errors []SdkAutomationValidationError `json:"errors,omitempty"`
}

// NewV1SdkAutomationPlaybookConfigsPostResponse instantiates a new V1SdkAutomationPlaybookConfigsPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookConfigsPostResponse() *V1SdkAutomationPlaybookConfigsPostResponse {
	this := V1SdkAutomationPlaybookConfigsPostResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookConfigsPostResponseWithDefaults instantiates a new V1SdkAutomationPlaybookConfigsPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookConfigsPostResponseWithDefaults() *V1SdkAutomationPlaybookConfigsPostResponse {
	this := V1SdkAutomationPlaybookConfigsPostResponse{}
	return &this
}

// GetConfigId returns the ConfigId field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsPostResponse) GetConfigId() string {
	if o == nil || IsNil(o.ConfigId) {
		var ret string
		return ret
	}
	return *o.ConfigId
}

// GetConfigIdOk returns a tuple with the ConfigId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsPostResponse) GetConfigIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConfigId) {
		return nil, false
	}
	return o.ConfigId, true
}

// HasConfigId returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsPostResponse) HasConfigId() bool {
	if o != nil && !IsNil(o.ConfigId) {
		return true
	}

	return false
}

// SetConfigId gets a reference to the given string and assigns it to the ConfigId field.
func (o *V1SdkAutomationPlaybookConfigsPostResponse) SetConfigId(v string) {
	o.ConfigId = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsPostResponse) GetErrors() []SdkAutomationValidationError {
	if o == nil || IsNil(o.Errors) {
		var ret []SdkAutomationValidationError
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsPostResponse) GetErrorsOk() ([]SdkAutomationValidationError, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsPostResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []SdkAutomationValidationError and assigns it to the Errors field.
func (o *V1SdkAutomationPlaybookConfigsPostResponse) SetErrors(v []SdkAutomationValidationError) {
	o.Errors = v
}

func (o V1SdkAutomationPlaybookConfigsPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookConfigsPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConfigId) {
		toSerialize["configId"] = o.ConfigId
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookConfigsPostResponse struct {
	value *V1SdkAutomationPlaybookConfigsPostResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookConfigsPostResponse) Get() *V1SdkAutomationPlaybookConfigsPostResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookConfigsPostResponse) Set(val *V1SdkAutomationPlaybookConfigsPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookConfigsPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookConfigsPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookConfigsPostResponse(val *V1SdkAutomationPlaybookConfigsPostResponse) *NullableV1SdkAutomationPlaybookConfigsPostResponse {
	return &NullableV1SdkAutomationPlaybookConfigsPostResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookConfigsPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookConfigsPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


