/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookJobsJobIdAbortPutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookJobsJobIdAbortPutResponse{}

// V1SdkAutomationPlaybookJobsJobIdAbortPutResponse struct for V1SdkAutomationPlaybookJobsJobIdAbortPutResponse
type V1SdkAutomationPlaybookJobsJobIdAbortPutResponse struct {
	// Job status after abort (typically ABORTED)
	Status *string `json:"status,omitempty"`
}

// NewV1SdkAutomationPlaybookJobsJobIdAbortPutResponse instantiates a new V1SdkAutomationPlaybookJobsJobIdAbortPutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookJobsJobIdAbortPutResponse() *V1SdkAutomationPlaybookJobsJobIdAbortPutResponse {
	this := V1SdkAutomationPlaybookJobsJobIdAbortPutResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookJobsJobIdAbortPutResponseWithDefaults instantiates a new V1SdkAutomationPlaybookJobsJobIdAbortPutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookJobsJobIdAbortPutResponseWithDefaults() *V1SdkAutomationPlaybookJobsJobIdAbortPutResponse {
	this := V1SdkAutomationPlaybookJobsJobIdAbortPutResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdAbortPutResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdAbortPutResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdAbortPutResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1SdkAutomationPlaybookJobsJobIdAbortPutResponse) SetStatus(v string) {
	o.Status = &v
}

func (o V1SdkAutomationPlaybookJobsJobIdAbortPutResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookJobsJobIdAbortPutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookJobsJobIdAbortPutResponse struct {
	value *V1SdkAutomationPlaybookJobsJobIdAbortPutResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdAbortPutResponse) Get() *V1SdkAutomationPlaybookJobsJobIdAbortPutResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdAbortPutResponse) Set(val *V1SdkAutomationPlaybookJobsJobIdAbortPutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdAbortPutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdAbortPutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookJobsJobIdAbortPutResponse(val *V1SdkAutomationPlaybookJobsJobIdAbortPutResponse) *NullableV1SdkAutomationPlaybookJobsJobIdAbortPutResponse {
	return &NullableV1SdkAutomationPlaybookJobsJobIdAbortPutResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdAbortPutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdAbortPutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


