/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookConfigsConfigIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookConfigsConfigIdPutRequest{}

// V1SdkAutomationPlaybookConfigsConfigIdPutRequest struct for V1SdkAutomationPlaybookConfigsConfigIdPutRequest
type V1SdkAutomationPlaybookConfigsConfigIdPutRequest struct {
	// Optional description / notes update
	Description *string `json:"description,omitempty"`
	Files []SdkAutomationModuleFile `json:"files,omitempty"`
	// Optional display name update
	Name *string `json:"name,omitempty"`
}

// NewV1SdkAutomationPlaybookConfigsConfigIdPutRequest instantiates a new V1SdkAutomationPlaybookConfigsConfigIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookConfigsConfigIdPutRequest() *V1SdkAutomationPlaybookConfigsConfigIdPutRequest {
	this := V1SdkAutomationPlaybookConfigsConfigIdPutRequest{}
	return &this
}

// NewV1SdkAutomationPlaybookConfigsConfigIdPutRequestWithDefaults instantiates a new V1SdkAutomationPlaybookConfigsConfigIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookConfigsConfigIdPutRequestWithDefaults() *V1SdkAutomationPlaybookConfigsConfigIdPutRequest {
	this := V1SdkAutomationPlaybookConfigsConfigIdPutRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) SetDescription(v string) {
	o.Description = &v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) GetFiles() []SdkAutomationModuleFile {
	if o == nil || IsNil(o.Files) {
		var ret []SdkAutomationModuleFile
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) GetFilesOk() ([]SdkAutomationModuleFile, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []SdkAutomationModuleFile and assigns it to the Files field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) SetFiles(v []SdkAutomationModuleFile) {
	o.Files = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) SetName(v string) {
	o.Name = &v
}

func (o V1SdkAutomationPlaybookConfigsConfigIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookConfigsConfigIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookConfigsConfigIdPutRequest struct {
	value *V1SdkAutomationPlaybookConfigsConfigIdPutRequest
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdPutRequest) Get() *V1SdkAutomationPlaybookConfigsConfigIdPutRequest {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdPutRequest) Set(val *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookConfigsConfigIdPutRequest(val *V1SdkAutomationPlaybookConfigsConfigIdPutRequest) *NullableV1SdkAutomationPlaybookConfigsConfigIdPutRequest {
	return &NullableV1SdkAutomationPlaybookConfigsConfigIdPutRequest{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


