/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1ExtranetB2bProducerPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ExtranetB2bProducerPostRequest{}

// V1ExtranetB2bProducerPostRequest struct for V1ExtranetB2bProducerPostRequest
type V1ExtranetB2bProducerPostRequest struct {
	Policy ManaV2ExtranetServiceProducerPolicy `json:"policy"`
	// Producer service name (letters, digits, hyphens only) (required)
	ServiceName string `json:"serviceName"`
	// Branded extranet service type (peering_service, client_to_server, …) (required)
	ServiceType string `json:"serviceType"`
}

type _V1ExtranetB2bProducerPostRequest V1ExtranetB2bProducerPostRequest

// NewV1ExtranetB2bProducerPostRequest instantiates a new V1ExtranetB2bProducerPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ExtranetB2bProducerPostRequest(policy ManaV2ExtranetServiceProducerPolicy, serviceName string, serviceType string) *V1ExtranetB2bProducerPostRequest {
	this := V1ExtranetB2bProducerPostRequest{}
	this.Policy = policy
	this.ServiceName = serviceName
	this.ServiceType = serviceType
	return &this
}

// NewV1ExtranetB2bProducerPostRequestWithDefaults instantiates a new V1ExtranetB2bProducerPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ExtranetB2bProducerPostRequestWithDefaults() *V1ExtranetB2bProducerPostRequest {
	this := V1ExtranetB2bProducerPostRequest{}
	return &this
}

// GetPolicy returns the Policy field value
func (o *V1ExtranetB2bProducerPostRequest) GetPolicy() ManaV2ExtranetServiceProducerPolicy {
	if o == nil {
		var ret ManaV2ExtranetServiceProducerPolicy
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bProducerPostRequest) GetPolicyOk() (*ManaV2ExtranetServiceProducerPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Policy, true
}

// SetPolicy sets field value
func (o *V1ExtranetB2bProducerPostRequest) SetPolicy(v ManaV2ExtranetServiceProducerPolicy) {
	o.Policy = v
}

// GetServiceName returns the ServiceName field value
func (o *V1ExtranetB2bProducerPostRequest) GetServiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bProducerPostRequest) GetServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceName, true
}

// SetServiceName sets field value
func (o *V1ExtranetB2bProducerPostRequest) SetServiceName(v string) {
	o.ServiceName = v
}

// GetServiceType returns the ServiceType field value
func (o *V1ExtranetB2bProducerPostRequest) GetServiceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value
// and a boolean to check if the value has been set.
func (o *V1ExtranetB2bProducerPostRequest) GetServiceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceType, true
}

// SetServiceType sets field value
func (o *V1ExtranetB2bProducerPostRequest) SetServiceType(v string) {
	o.ServiceType = v
}

func (o V1ExtranetB2bProducerPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ExtranetB2bProducerPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy"] = o.Policy
	toSerialize["serviceName"] = o.ServiceName
	toSerialize["serviceType"] = o.ServiceType
	return toSerialize, nil
}

func (o *V1ExtranetB2bProducerPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"policy",
		"serviceName",
		"serviceType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ExtranetB2bProducerPostRequest := _V1ExtranetB2bProducerPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ExtranetB2bProducerPostRequest)

	if err != nil {
		return err
	}

	*o = V1ExtranetB2bProducerPostRequest(varV1ExtranetB2bProducerPostRequest)

	return err
}

type NullableV1ExtranetB2bProducerPostRequest struct {
	value *V1ExtranetB2bProducerPostRequest
	isSet bool
}

func (v NullableV1ExtranetB2bProducerPostRequest) Get() *V1ExtranetB2bProducerPostRequest {
	return v.value
}

func (v *NullableV1ExtranetB2bProducerPostRequest) Set(val *V1ExtranetB2bProducerPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ExtranetB2bProducerPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ExtranetB2bProducerPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ExtranetB2bProducerPostRequest(val *V1ExtranetB2bProducerPostRequest) *NullableV1ExtranetB2bProducerPostRequest {
	return &NullableV1ExtranetB2bProducerPostRequest{value: val, isSet: true}
}

func (v NullableV1ExtranetB2bProducerPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ExtranetB2bProducerPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


