/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the IamEnterprise type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IamEnterprise{}

// IamEnterprise struct for IamEnterprise
type IamEnterprise struct {
	AcceptEula *bool `json:"acceptEula,omitempty"`
	AccountType *string `json:"accountType,omitempty"`
	AdminEmail *string `json:"adminEmail,omitempty"`
	BackboneApisEnabled *bool `json:"backboneApisEnabled,omitempty"`
	CloudProvider *string `json:"cloudProvider,omitempty"`
	CompanyName *string `json:"companyName,omitempty"`
	Counts *IamCounts `json:"counts,omitempty"`
	CreditLimit *int32 `json:"creditLimit,omitempty"`
	Customers *map[string]IamCustomer `json:"customers,omitempty"`
	Description *string `json:"description,omitempty"`
	EnterpriseId *int64 `json:"enterpriseId,omitempty"`
	EulaAgreementDate *GoogleProtobufTimestamp `json:"eulaAgreementDate,omitempty"`
	ImpersonationEnabled *bool `json:"impersonationEnabled,omitempty"`
	Logo *string `json:"logo,omitempty"`
	MarketplaceId *string `json:"marketplaceId,omitempty"`
	ParentCompanyName *string `json:"parentCompanyName,omitempty"`
	ParentEnterpriseId *int64 `json:"parentEnterpriseId,omitempty"`
	PortalBanner *string `json:"portalBanner,omitempty"`
	ProxyTenantId *int64 `json:"proxyTenantId,omitempty"`
	SmallLogo *string `json:"smallLogo,omitempty"`
	TokenExpiry *string `json:"tokenExpiry,omitempty"`
}

// NewIamEnterprise instantiates a new IamEnterprise object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIamEnterprise() *IamEnterprise {
	this := IamEnterprise{}
	return &this
}

// NewIamEnterpriseWithDefaults instantiates a new IamEnterprise object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIamEnterpriseWithDefaults() *IamEnterprise {
	this := IamEnterprise{}
	return &this
}

// GetAcceptEula returns the AcceptEula field value if set, zero value otherwise.
func (o *IamEnterprise) GetAcceptEula() bool {
	if o == nil || IsNil(o.AcceptEula) {
		var ret bool
		return ret
	}
	return *o.AcceptEula
}

// GetAcceptEulaOk returns a tuple with the AcceptEula field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetAcceptEulaOk() (*bool, bool) {
	if o == nil || IsNil(o.AcceptEula) {
		return nil, false
	}
	return o.AcceptEula, true
}

// HasAcceptEula returns a boolean if a field has been set.
func (o *IamEnterprise) HasAcceptEula() bool {
	if o != nil && !IsNil(o.AcceptEula) {
		return true
	}

	return false
}

// SetAcceptEula gets a reference to the given bool and assigns it to the AcceptEula field.
func (o *IamEnterprise) SetAcceptEula(v bool) {
	o.AcceptEula = &v
}

// GetAccountType returns the AccountType field value if set, zero value otherwise.
func (o *IamEnterprise) GetAccountType() string {
	if o == nil || IsNil(o.AccountType) {
		var ret string
		return ret
	}
	return *o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetAccountTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AccountType) {
		return nil, false
	}
	return o.AccountType, true
}

// HasAccountType returns a boolean if a field has been set.
func (o *IamEnterprise) HasAccountType() bool {
	if o != nil && !IsNil(o.AccountType) {
		return true
	}

	return false
}

// SetAccountType gets a reference to the given string and assigns it to the AccountType field.
func (o *IamEnterprise) SetAccountType(v string) {
	o.AccountType = &v
}

// GetAdminEmail returns the AdminEmail field value if set, zero value otherwise.
func (o *IamEnterprise) GetAdminEmail() string {
	if o == nil || IsNil(o.AdminEmail) {
		var ret string
		return ret
	}
	return *o.AdminEmail
}

// GetAdminEmailOk returns a tuple with the AdminEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetAdminEmailOk() (*string, bool) {
	if o == nil || IsNil(o.AdminEmail) {
		return nil, false
	}
	return o.AdminEmail, true
}

// HasAdminEmail returns a boolean if a field has been set.
func (o *IamEnterprise) HasAdminEmail() bool {
	if o != nil && !IsNil(o.AdminEmail) {
		return true
	}

	return false
}

// SetAdminEmail gets a reference to the given string and assigns it to the AdminEmail field.
func (o *IamEnterprise) SetAdminEmail(v string) {
	o.AdminEmail = &v
}

// GetBackboneApisEnabled returns the BackboneApisEnabled field value if set, zero value otherwise.
func (o *IamEnterprise) GetBackboneApisEnabled() bool {
	if o == nil || IsNil(o.BackboneApisEnabled) {
		var ret bool
		return ret
	}
	return *o.BackboneApisEnabled
}

// GetBackboneApisEnabledOk returns a tuple with the BackboneApisEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetBackboneApisEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.BackboneApisEnabled) {
		return nil, false
	}
	return o.BackboneApisEnabled, true
}

// HasBackboneApisEnabled returns a boolean if a field has been set.
func (o *IamEnterprise) HasBackboneApisEnabled() bool {
	if o != nil && !IsNil(o.BackboneApisEnabled) {
		return true
	}

	return false
}

// SetBackboneApisEnabled gets a reference to the given bool and assigns it to the BackboneApisEnabled field.
func (o *IamEnterprise) SetBackboneApisEnabled(v bool) {
	o.BackboneApisEnabled = &v
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise.
func (o *IamEnterprise) GetCloudProvider() string {
	if o == nil || IsNil(o.CloudProvider) {
		var ret string
		return ret
	}
	return *o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetCloudProviderOk() (*string, bool) {
	if o == nil || IsNil(o.CloudProvider) {
		return nil, false
	}
	return o.CloudProvider, true
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *IamEnterprise) HasCloudProvider() bool {
	if o != nil && !IsNil(o.CloudProvider) {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given string and assigns it to the CloudProvider field.
func (o *IamEnterprise) SetCloudProvider(v string) {
	o.CloudProvider = &v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *IamEnterprise) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *IamEnterprise) HasCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *IamEnterprise) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetCounts returns the Counts field value if set, zero value otherwise.
func (o *IamEnterprise) GetCounts() IamCounts {
	if o == nil || IsNil(o.Counts) {
		var ret IamCounts
		return ret
	}
	return *o.Counts
}

// GetCountsOk returns a tuple with the Counts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetCountsOk() (*IamCounts, bool) {
	if o == nil || IsNil(o.Counts) {
		return nil, false
	}
	return o.Counts, true
}

// HasCounts returns a boolean if a field has been set.
func (o *IamEnterprise) HasCounts() bool {
	if o != nil && !IsNil(o.Counts) {
		return true
	}

	return false
}

// SetCounts gets a reference to the given IamCounts and assigns it to the Counts field.
func (o *IamEnterprise) SetCounts(v IamCounts) {
	o.Counts = &v
}

// GetCreditLimit returns the CreditLimit field value if set, zero value otherwise.
func (o *IamEnterprise) GetCreditLimit() int32 {
	if o == nil || IsNil(o.CreditLimit) {
		var ret int32
		return ret
	}
	return *o.CreditLimit
}

// GetCreditLimitOk returns a tuple with the CreditLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetCreditLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditLimit) {
		return nil, false
	}
	return o.CreditLimit, true
}

// HasCreditLimit returns a boolean if a field has been set.
func (o *IamEnterprise) HasCreditLimit() bool {
	if o != nil && !IsNil(o.CreditLimit) {
		return true
	}

	return false
}

// SetCreditLimit gets a reference to the given int32 and assigns it to the CreditLimit field.
func (o *IamEnterprise) SetCreditLimit(v int32) {
	o.CreditLimit = &v
}

// GetCustomers returns the Customers field value if set, zero value otherwise.
func (o *IamEnterprise) GetCustomers() map[string]IamCustomer {
	if o == nil || IsNil(o.Customers) {
		var ret map[string]IamCustomer
		return ret
	}
	return *o.Customers
}

// GetCustomersOk returns a tuple with the Customers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetCustomersOk() (*map[string]IamCustomer, bool) {
	if o == nil || IsNil(o.Customers) {
		return nil, false
	}
	return o.Customers, true
}

// HasCustomers returns a boolean if a field has been set.
func (o *IamEnterprise) HasCustomers() bool {
	if o != nil && !IsNil(o.Customers) {
		return true
	}

	return false
}

// SetCustomers gets a reference to the given map[string]IamCustomer and assigns it to the Customers field.
func (o *IamEnterprise) SetCustomers(v map[string]IamCustomer) {
	o.Customers = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *IamEnterprise) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *IamEnterprise) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *IamEnterprise) SetDescription(v string) {
	o.Description = &v
}

// GetEnterpriseId returns the EnterpriseId field value if set, zero value otherwise.
func (o *IamEnterprise) GetEnterpriseId() int64 {
	if o == nil || IsNil(o.EnterpriseId) {
		var ret int64
		return ret
	}
	return *o.EnterpriseId
}

// GetEnterpriseIdOk returns a tuple with the EnterpriseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetEnterpriseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.EnterpriseId) {
		return nil, false
	}
	return o.EnterpriseId, true
}

// HasEnterpriseId returns a boolean if a field has been set.
func (o *IamEnterprise) HasEnterpriseId() bool {
	if o != nil && !IsNil(o.EnterpriseId) {
		return true
	}

	return false
}

// SetEnterpriseId gets a reference to the given int64 and assigns it to the EnterpriseId field.
func (o *IamEnterprise) SetEnterpriseId(v int64) {
	o.EnterpriseId = &v
}

// GetEulaAgreementDate returns the EulaAgreementDate field value if set, zero value otherwise.
func (o *IamEnterprise) GetEulaAgreementDate() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.EulaAgreementDate) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.EulaAgreementDate
}

// GetEulaAgreementDateOk returns a tuple with the EulaAgreementDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetEulaAgreementDateOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.EulaAgreementDate) {
		return nil, false
	}
	return o.EulaAgreementDate, true
}

// HasEulaAgreementDate returns a boolean if a field has been set.
func (o *IamEnterprise) HasEulaAgreementDate() bool {
	if o != nil && !IsNil(o.EulaAgreementDate) {
		return true
	}

	return false
}

// SetEulaAgreementDate gets a reference to the given GoogleProtobufTimestamp and assigns it to the EulaAgreementDate field.
func (o *IamEnterprise) SetEulaAgreementDate(v GoogleProtobufTimestamp) {
	o.EulaAgreementDate = &v
}

// GetImpersonationEnabled returns the ImpersonationEnabled field value if set, zero value otherwise.
func (o *IamEnterprise) GetImpersonationEnabled() bool {
	if o == nil || IsNil(o.ImpersonationEnabled) {
		var ret bool
		return ret
	}
	return *o.ImpersonationEnabled
}

// GetImpersonationEnabledOk returns a tuple with the ImpersonationEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetImpersonationEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ImpersonationEnabled) {
		return nil, false
	}
	return o.ImpersonationEnabled, true
}

// HasImpersonationEnabled returns a boolean if a field has been set.
func (o *IamEnterprise) HasImpersonationEnabled() bool {
	if o != nil && !IsNil(o.ImpersonationEnabled) {
		return true
	}

	return false
}

// SetImpersonationEnabled gets a reference to the given bool and assigns it to the ImpersonationEnabled field.
func (o *IamEnterprise) SetImpersonationEnabled(v bool) {
	o.ImpersonationEnabled = &v
}

// GetLogo returns the Logo field value if set, zero value otherwise.
func (o *IamEnterprise) GetLogo() string {
	if o == nil || IsNil(o.Logo) {
		var ret string
		return ret
	}
	return *o.Logo
}

// GetLogoOk returns a tuple with the Logo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetLogoOk() (*string, bool) {
	if o == nil || IsNil(o.Logo) {
		return nil, false
	}
	return o.Logo, true
}

// HasLogo returns a boolean if a field has been set.
func (o *IamEnterprise) HasLogo() bool {
	if o != nil && !IsNil(o.Logo) {
		return true
	}

	return false
}

// SetLogo gets a reference to the given string and assigns it to the Logo field.
func (o *IamEnterprise) SetLogo(v string) {
	o.Logo = &v
}

// GetMarketplaceId returns the MarketplaceId field value if set, zero value otherwise.
func (o *IamEnterprise) GetMarketplaceId() string {
	if o == nil || IsNil(o.MarketplaceId) {
		var ret string
		return ret
	}
	return *o.MarketplaceId
}

// GetMarketplaceIdOk returns a tuple with the MarketplaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetMarketplaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.MarketplaceId) {
		return nil, false
	}
	return o.MarketplaceId, true
}

// HasMarketplaceId returns a boolean if a field has been set.
func (o *IamEnterprise) HasMarketplaceId() bool {
	if o != nil && !IsNil(o.MarketplaceId) {
		return true
	}

	return false
}

// SetMarketplaceId gets a reference to the given string and assigns it to the MarketplaceId field.
func (o *IamEnterprise) SetMarketplaceId(v string) {
	o.MarketplaceId = &v
}

// GetParentCompanyName returns the ParentCompanyName field value if set, zero value otherwise.
func (o *IamEnterprise) GetParentCompanyName() string {
	if o == nil || IsNil(o.ParentCompanyName) {
		var ret string
		return ret
	}
	return *o.ParentCompanyName
}

// GetParentCompanyNameOk returns a tuple with the ParentCompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetParentCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.ParentCompanyName) {
		return nil, false
	}
	return o.ParentCompanyName, true
}

// HasParentCompanyName returns a boolean if a field has been set.
func (o *IamEnterprise) HasParentCompanyName() bool {
	if o != nil && !IsNil(o.ParentCompanyName) {
		return true
	}

	return false
}

// SetParentCompanyName gets a reference to the given string and assigns it to the ParentCompanyName field.
func (o *IamEnterprise) SetParentCompanyName(v string) {
	o.ParentCompanyName = &v
}

// GetParentEnterpriseId returns the ParentEnterpriseId field value if set, zero value otherwise.
func (o *IamEnterprise) GetParentEnterpriseId() int64 {
	if o == nil || IsNil(o.ParentEnterpriseId) {
		var ret int64
		return ret
	}
	return *o.ParentEnterpriseId
}

// GetParentEnterpriseIdOk returns a tuple with the ParentEnterpriseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetParentEnterpriseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ParentEnterpriseId) {
		return nil, false
	}
	return o.ParentEnterpriseId, true
}

// HasParentEnterpriseId returns a boolean if a field has been set.
func (o *IamEnterprise) HasParentEnterpriseId() bool {
	if o != nil && !IsNil(o.ParentEnterpriseId) {
		return true
	}

	return false
}

// SetParentEnterpriseId gets a reference to the given int64 and assigns it to the ParentEnterpriseId field.
func (o *IamEnterprise) SetParentEnterpriseId(v int64) {
	o.ParentEnterpriseId = &v
}

// GetPortalBanner returns the PortalBanner field value if set, zero value otherwise.
func (o *IamEnterprise) GetPortalBanner() string {
	if o == nil || IsNil(o.PortalBanner) {
		var ret string
		return ret
	}
	return *o.PortalBanner
}

// GetPortalBannerOk returns a tuple with the PortalBanner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetPortalBannerOk() (*string, bool) {
	if o == nil || IsNil(o.PortalBanner) {
		return nil, false
	}
	return o.PortalBanner, true
}

// HasPortalBanner returns a boolean if a field has been set.
func (o *IamEnterprise) HasPortalBanner() bool {
	if o != nil && !IsNil(o.PortalBanner) {
		return true
	}

	return false
}

// SetPortalBanner gets a reference to the given string and assigns it to the PortalBanner field.
func (o *IamEnterprise) SetPortalBanner(v string) {
	o.PortalBanner = &v
}

// GetProxyTenantId returns the ProxyTenantId field value if set, zero value otherwise.
func (o *IamEnterprise) GetProxyTenantId() int64 {
	if o == nil || IsNil(o.ProxyTenantId) {
		var ret int64
		return ret
	}
	return *o.ProxyTenantId
}

// GetProxyTenantIdOk returns a tuple with the ProxyTenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetProxyTenantIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ProxyTenantId) {
		return nil, false
	}
	return o.ProxyTenantId, true
}

// HasProxyTenantId returns a boolean if a field has been set.
func (o *IamEnterprise) HasProxyTenantId() bool {
	if o != nil && !IsNil(o.ProxyTenantId) {
		return true
	}

	return false
}

// SetProxyTenantId gets a reference to the given int64 and assigns it to the ProxyTenantId field.
func (o *IamEnterprise) SetProxyTenantId(v int64) {
	o.ProxyTenantId = &v
}

// GetSmallLogo returns the SmallLogo field value if set, zero value otherwise.
func (o *IamEnterprise) GetSmallLogo() string {
	if o == nil || IsNil(o.SmallLogo) {
		var ret string
		return ret
	}
	return *o.SmallLogo
}

// GetSmallLogoOk returns a tuple with the SmallLogo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetSmallLogoOk() (*string, bool) {
	if o == nil || IsNil(o.SmallLogo) {
		return nil, false
	}
	return o.SmallLogo, true
}

// HasSmallLogo returns a boolean if a field has been set.
func (o *IamEnterprise) HasSmallLogo() bool {
	if o != nil && !IsNil(o.SmallLogo) {
		return true
	}

	return false
}

// SetSmallLogo gets a reference to the given string and assigns it to the SmallLogo field.
func (o *IamEnterprise) SetSmallLogo(v string) {
	o.SmallLogo = &v
}

// GetTokenExpiry returns the TokenExpiry field value if set, zero value otherwise.
func (o *IamEnterprise) GetTokenExpiry() string {
	if o == nil || IsNil(o.TokenExpiry) {
		var ret string
		return ret
	}
	return *o.TokenExpiry
}

// GetTokenExpiryOk returns a tuple with the TokenExpiry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IamEnterprise) GetTokenExpiryOk() (*string, bool) {
	if o == nil || IsNil(o.TokenExpiry) {
		return nil, false
	}
	return o.TokenExpiry, true
}

// HasTokenExpiry returns a boolean if a field has been set.
func (o *IamEnterprise) HasTokenExpiry() bool {
	if o != nil && !IsNil(o.TokenExpiry) {
		return true
	}

	return false
}

// SetTokenExpiry gets a reference to the given string and assigns it to the TokenExpiry field.
func (o *IamEnterprise) SetTokenExpiry(v string) {
	o.TokenExpiry = &v
}

func (o IamEnterprise) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IamEnterprise) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AcceptEula) {
		toSerialize["acceptEula"] = o.AcceptEula
	}
	if !IsNil(o.AccountType) {
		toSerialize["accountType"] = o.AccountType
	}
	if !IsNil(o.AdminEmail) {
		toSerialize["adminEmail"] = o.AdminEmail
	}
	if !IsNil(o.BackboneApisEnabled) {
		toSerialize["backboneApisEnabled"] = o.BackboneApisEnabled
	}
	if !IsNil(o.CloudProvider) {
		toSerialize["cloudProvider"] = o.CloudProvider
	}
	if !IsNil(o.CompanyName) {
		toSerialize["companyName"] = o.CompanyName
	}
	if !IsNil(o.Counts) {
		toSerialize["counts"] = o.Counts
	}
	if !IsNil(o.CreditLimit) {
		toSerialize["creditLimit"] = o.CreditLimit
	}
	if !IsNil(o.Customers) {
		toSerialize["customers"] = o.Customers
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.EnterpriseId) {
		toSerialize["enterpriseId"] = o.EnterpriseId
	}
	if !IsNil(o.EulaAgreementDate) {
		toSerialize["eulaAgreementDate"] = o.EulaAgreementDate
	}
	if !IsNil(o.ImpersonationEnabled) {
		toSerialize["impersonationEnabled"] = o.ImpersonationEnabled
	}
	if !IsNil(o.Logo) {
		toSerialize["logo"] = o.Logo
	}
	if !IsNil(o.MarketplaceId) {
		toSerialize["marketplaceId"] = o.MarketplaceId
	}
	if !IsNil(o.ParentCompanyName) {
		toSerialize["parentCompanyName"] = o.ParentCompanyName
	}
	if !IsNil(o.ParentEnterpriseId) {
		toSerialize["parentEnterpriseId"] = o.ParentEnterpriseId
	}
	if !IsNil(o.PortalBanner) {
		toSerialize["portalBanner"] = o.PortalBanner
	}
	if !IsNil(o.ProxyTenantId) {
		toSerialize["proxyTenantId"] = o.ProxyTenantId
	}
	if !IsNil(o.SmallLogo) {
		toSerialize["smallLogo"] = o.SmallLogo
	}
	if !IsNil(o.TokenExpiry) {
		toSerialize["tokenExpiry"] = o.TokenExpiry
	}
	return toSerialize, nil
}

type NullableIamEnterprise struct {
	value *IamEnterprise
	isSet bool
}

func (v NullableIamEnterprise) Get() *IamEnterprise {
	return v.value
}

func (v *NullableIamEnterprise) Set(val *IamEnterprise) {
	v.value = val
	v.isSet = true
}

func (v NullableIamEnterprise) IsSet() bool {
	return v.isSet
}

func (v *NullableIamEnterprise) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIamEnterprise(val *IamEnterprise) *NullableIamEnterprise {
	return &NullableIamEnterprise{value: val, isSet: true}
}

func (v NullableIamEnterprise) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIamEnterprise) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


