/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookJobsJobIdApprovePutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookJobsJobIdApprovePutResponse{}

// V1SdkAutomationPlaybookJobsJobIdApprovePutResponse struct for V1SdkAutomationPlaybookJobsJobIdApprovePutResponse
type V1SdkAutomationPlaybookJobsJobIdApprovePutResponse struct {
	// Job status after approve was accepted
	Status *string `json:"status,omitempty"`
}

// NewV1SdkAutomationPlaybookJobsJobIdApprovePutResponse instantiates a new V1SdkAutomationPlaybookJobsJobIdApprovePutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookJobsJobIdApprovePutResponse() *V1SdkAutomationPlaybookJobsJobIdApprovePutResponse {
	this := V1SdkAutomationPlaybookJobsJobIdApprovePutResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookJobsJobIdApprovePutResponseWithDefaults instantiates a new V1SdkAutomationPlaybookJobsJobIdApprovePutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookJobsJobIdApprovePutResponseWithDefaults() *V1SdkAutomationPlaybookJobsJobIdApprovePutResponse {
	this := V1SdkAutomationPlaybookJobsJobIdApprovePutResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdApprovePutResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdApprovePutResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdApprovePutResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1SdkAutomationPlaybookJobsJobIdApprovePutResponse) SetStatus(v string) {
	o.Status = &v
}

func (o V1SdkAutomationPlaybookJobsJobIdApprovePutResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookJobsJobIdApprovePutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookJobsJobIdApprovePutResponse struct {
	value *V1SdkAutomationPlaybookJobsJobIdApprovePutResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdApprovePutResponse) Get() *V1SdkAutomationPlaybookJobsJobIdApprovePutResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdApprovePutResponse) Set(val *V1SdkAutomationPlaybookJobsJobIdApprovePutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdApprovePutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdApprovePutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookJobsJobIdApprovePutResponse(val *V1SdkAutomationPlaybookJobsJobIdApprovePutResponse) *NullableV1SdkAutomationPlaybookJobsJobIdApprovePutResponse {
	return &NullableV1SdkAutomationPlaybookJobsJobIdApprovePutResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdApprovePutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdApprovePutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


