/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse{}

// V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse struct for V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse
type V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse struct {
	// Created job id for the dry-run
	JobId *string `json:"jobId,omitempty"`
	// Initial job status after enqueue (typically QUEUED or DRY_RUNNING)
	Status *string `json:"status,omitempty"`
}

// NewV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse instantiates a new V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse() *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse {
	this := V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponseWithDefaults instantiates a new V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponseWithDefaults() *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse {
	this := V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) SetJobId(v string) {
	o.JobId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) SetStatus(v string) {
	o.Status = &v
}

func (o V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobId) {
		toSerialize["jobId"] = o.JobId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse struct {
	value *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) Get() *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) Set(val *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse(val *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) *NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse {
	return &NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


