/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest{}

// V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest struct for V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest
type V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest struct {
	// When true, request ansible -vvv for this dry-run
	VerboseLogs *bool `json:"verboseLogs,omitempty"`
}

// NewV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest instantiates a new V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest() *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest {
	this := V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest{}
	return &this
}

// NewV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequestWithDefaults instantiates a new V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequestWithDefaults() *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest {
	this := V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest{}
	return &this
}

// GetVerboseLogs returns the VerboseLogs field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) GetVerboseLogs() bool {
	if o == nil || IsNil(o.VerboseLogs) {
		var ret bool
		return ret
	}
	return *o.VerboseLogs
}

// GetVerboseLogsOk returns a tuple with the VerboseLogs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) GetVerboseLogsOk() (*bool, bool) {
	if o == nil || IsNil(o.VerboseLogs) {
		return nil, false
	}
	return o.VerboseLogs, true
}

// HasVerboseLogs returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) HasVerboseLogs() bool {
	if o != nil && !IsNil(o.VerboseLogs) {
		return true
	}

	return false
}

// SetVerboseLogs gets a reference to the given bool and assigns it to the VerboseLogs field.
func (o *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) SetVerboseLogs(v bool) {
	o.VerboseLogs = &v
}

func (o V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VerboseLogs) {
		toSerialize["verboseLogs"] = o.VerboseLogs
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest struct {
	value *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) Get() *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) Set(val *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest(val *V1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) *NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest {
	return &NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookConfigsConfigIdDryRunPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


