/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1PvifPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1PvifPostRequest{}

// V1PvifPostRequest struct for V1PvifPostRequest
type V1PvifPostRequest struct {
	Advertisement *ManaV2SiteInformation `json:"advertisement,omitempty"`
	ConsumerLanSegments map[string]ManaV2PublicVifGatewayConsumerLanDevices `json:"consumerLanSegments"`
	CoveringPrefixes []string `json:"coveringPrefixes,omitempty"`
	GatewayBgpNeighbors map[string]ManaV2BgpNeighborConfig `json:"gatewayBgpNeighbors"`
	// Producer LAN segment (VRF) on gateway appliances (required)
	LanSegmentId int64 `json:"lanSegmentId"`
	NatPrefixStrategy ManaV2PublicVifGatewayNatPrefixStrategy `json:"natPrefixStrategy"`
	// Graphiant region for gateway appliances (required)
	RegionId int32 `json:"regionId"`
	// Producer service name (letters, digits, hyphens only) (required)
	ServiceName string `json:"serviceName"`
	// Storage provider; each gateway appliance must match region and provider (required)
	StorageProvider string `json:"storageProvider"`
}

type _V1PvifPostRequest V1PvifPostRequest

// NewV1PvifPostRequest instantiates a new V1PvifPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1PvifPostRequest(consumerLanSegments map[string]ManaV2PublicVifGatewayConsumerLanDevices, gatewayBgpNeighbors map[string]ManaV2BgpNeighborConfig, lanSegmentId int64, natPrefixStrategy ManaV2PublicVifGatewayNatPrefixStrategy, regionId int32, serviceName string, storageProvider string) *V1PvifPostRequest {
	this := V1PvifPostRequest{}
	this.ConsumerLanSegments = consumerLanSegments
	this.GatewayBgpNeighbors = gatewayBgpNeighbors
	this.LanSegmentId = lanSegmentId
	this.NatPrefixStrategy = natPrefixStrategy
	this.RegionId = regionId
	this.ServiceName = serviceName
	this.StorageProvider = storageProvider
	return &this
}

// NewV1PvifPostRequestWithDefaults instantiates a new V1PvifPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1PvifPostRequestWithDefaults() *V1PvifPostRequest {
	this := V1PvifPostRequest{}
	return &this
}

// GetAdvertisement returns the Advertisement field value if set, zero value otherwise.
func (o *V1PvifPostRequest) GetAdvertisement() ManaV2SiteInformation {
	if o == nil || IsNil(o.Advertisement) {
		var ret ManaV2SiteInformation
		return ret
	}
	return *o.Advertisement
}

// GetAdvertisementOk returns a tuple with the Advertisement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PvifPostRequest) GetAdvertisementOk() (*ManaV2SiteInformation, bool) {
	if o == nil || IsNil(o.Advertisement) {
		return nil, false
	}
	return o.Advertisement, true
}

// HasAdvertisement returns a boolean if a field has been set.
func (o *V1PvifPostRequest) HasAdvertisement() bool {
	if o != nil && !IsNil(o.Advertisement) {
		return true
	}

	return false
}

// SetAdvertisement gets a reference to the given ManaV2SiteInformation and assigns it to the Advertisement field.
func (o *V1PvifPostRequest) SetAdvertisement(v ManaV2SiteInformation) {
	o.Advertisement = &v
}

// GetConsumerLanSegments returns the ConsumerLanSegments field value
func (o *V1PvifPostRequest) GetConsumerLanSegments() map[string]ManaV2PublicVifGatewayConsumerLanDevices {
	if o == nil {
		var ret map[string]ManaV2PublicVifGatewayConsumerLanDevices
		return ret
	}

	return o.ConsumerLanSegments
}

// GetConsumerLanSegmentsOk returns a tuple with the ConsumerLanSegments field value
// and a boolean to check if the value has been set.
func (o *V1PvifPostRequest) GetConsumerLanSegmentsOk() (*map[string]ManaV2PublicVifGatewayConsumerLanDevices, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsumerLanSegments, true
}

// SetConsumerLanSegments sets field value
func (o *V1PvifPostRequest) SetConsumerLanSegments(v map[string]ManaV2PublicVifGatewayConsumerLanDevices) {
	o.ConsumerLanSegments = v
}

// GetCoveringPrefixes returns the CoveringPrefixes field value if set, zero value otherwise.
func (o *V1PvifPostRequest) GetCoveringPrefixes() []string {
	if o == nil || IsNil(o.CoveringPrefixes) {
		var ret []string
		return ret
	}
	return o.CoveringPrefixes
}

// GetCoveringPrefixesOk returns a tuple with the CoveringPrefixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PvifPostRequest) GetCoveringPrefixesOk() ([]string, bool) {
	if o == nil || IsNil(o.CoveringPrefixes) {
		return nil, false
	}
	return o.CoveringPrefixes, true
}

// HasCoveringPrefixes returns a boolean if a field has been set.
func (o *V1PvifPostRequest) HasCoveringPrefixes() bool {
	if o != nil && !IsNil(o.CoveringPrefixes) {
		return true
	}

	return false
}

// SetCoveringPrefixes gets a reference to the given []string and assigns it to the CoveringPrefixes field.
func (o *V1PvifPostRequest) SetCoveringPrefixes(v []string) {
	o.CoveringPrefixes = v
}

// GetGatewayBgpNeighbors returns the GatewayBgpNeighbors field value
func (o *V1PvifPostRequest) GetGatewayBgpNeighbors() map[string]ManaV2BgpNeighborConfig {
	if o == nil {
		var ret map[string]ManaV2BgpNeighborConfig
		return ret
	}

	return o.GatewayBgpNeighbors
}

// GetGatewayBgpNeighborsOk returns a tuple with the GatewayBgpNeighbors field value
// and a boolean to check if the value has been set.
func (o *V1PvifPostRequest) GetGatewayBgpNeighborsOk() (*map[string]ManaV2BgpNeighborConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayBgpNeighbors, true
}

// SetGatewayBgpNeighbors sets field value
func (o *V1PvifPostRequest) SetGatewayBgpNeighbors(v map[string]ManaV2BgpNeighborConfig) {
	o.GatewayBgpNeighbors = v
}

// GetLanSegmentId returns the LanSegmentId field value
func (o *V1PvifPostRequest) GetLanSegmentId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LanSegmentId
}

// GetLanSegmentIdOk returns a tuple with the LanSegmentId field value
// and a boolean to check if the value has been set.
func (o *V1PvifPostRequest) GetLanSegmentIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LanSegmentId, true
}

// SetLanSegmentId sets field value
func (o *V1PvifPostRequest) SetLanSegmentId(v int64) {
	o.LanSegmentId = v
}

// GetNatPrefixStrategy returns the NatPrefixStrategy field value
func (o *V1PvifPostRequest) GetNatPrefixStrategy() ManaV2PublicVifGatewayNatPrefixStrategy {
	if o == nil {
		var ret ManaV2PublicVifGatewayNatPrefixStrategy
		return ret
	}

	return o.NatPrefixStrategy
}

// GetNatPrefixStrategyOk returns a tuple with the NatPrefixStrategy field value
// and a boolean to check if the value has been set.
func (o *V1PvifPostRequest) GetNatPrefixStrategyOk() (*ManaV2PublicVifGatewayNatPrefixStrategy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NatPrefixStrategy, true
}

// SetNatPrefixStrategy sets field value
func (o *V1PvifPostRequest) SetNatPrefixStrategy(v ManaV2PublicVifGatewayNatPrefixStrategy) {
	o.NatPrefixStrategy = v
}

// GetRegionId returns the RegionId field value
func (o *V1PvifPostRequest) GetRegionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value
// and a boolean to check if the value has been set.
func (o *V1PvifPostRequest) GetRegionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionId, true
}

// SetRegionId sets field value
func (o *V1PvifPostRequest) SetRegionId(v int32) {
	o.RegionId = v
}

// GetServiceName returns the ServiceName field value
func (o *V1PvifPostRequest) GetServiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value
// and a boolean to check if the value has been set.
func (o *V1PvifPostRequest) GetServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceName, true
}

// SetServiceName sets field value
func (o *V1PvifPostRequest) SetServiceName(v string) {
	o.ServiceName = v
}

// GetStorageProvider returns the StorageProvider field value
func (o *V1PvifPostRequest) GetStorageProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StorageProvider
}

// GetStorageProviderOk returns a tuple with the StorageProvider field value
// and a boolean to check if the value has been set.
func (o *V1PvifPostRequest) GetStorageProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageProvider, true
}

// SetStorageProvider sets field value
func (o *V1PvifPostRequest) SetStorageProvider(v string) {
	o.StorageProvider = v
}

func (o V1PvifPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1PvifPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Advertisement) {
		toSerialize["advertisement"] = o.Advertisement
	}
	toSerialize["consumerLanSegments"] = o.ConsumerLanSegments
	if !IsNil(o.CoveringPrefixes) {
		toSerialize["coveringPrefixes"] = o.CoveringPrefixes
	}
	toSerialize["gatewayBgpNeighbors"] = o.GatewayBgpNeighbors
	toSerialize["lanSegmentId"] = o.LanSegmentId
	toSerialize["natPrefixStrategy"] = o.NatPrefixStrategy
	toSerialize["regionId"] = o.RegionId
	toSerialize["serviceName"] = o.ServiceName
	toSerialize["storageProvider"] = o.StorageProvider
	return toSerialize, nil
}

func (o *V1PvifPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"consumerLanSegments",
		"gatewayBgpNeighbors",
		"lanSegmentId",
		"natPrefixStrategy",
		"regionId",
		"serviceName",
		"storageProvider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1PvifPostRequest := _V1PvifPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1PvifPostRequest)

	if err != nil {
		return err
	}

	*o = V1PvifPostRequest(varV1PvifPostRequest)

	return err
}

type NullableV1PvifPostRequest struct {
	value *V1PvifPostRequest
	isSet bool
}

func (v NullableV1PvifPostRequest) Get() *V1PvifPostRequest {
	return v.value
}

func (v *NullableV1PvifPostRequest) Set(val *V1PvifPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PvifPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PvifPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PvifPostRequest(val *V1PvifPostRequest) *NullableV1PvifPostRequest {
	return &NullableV1PvifPostRequest{value: val, isSet: true}
}

func (v NullableV1PvifPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PvifPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


