/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookConfigsGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookConfigsGetResponse{}

// V1SdkAutomationPlaybookConfigsGetResponse struct for V1SdkAutomationPlaybookConfigsGetResponse
type V1SdkAutomationPlaybookConfigsGetResponse struct {
	Configs []SdkAutomationPlaybookConfigSummary `json:"configs,omitempty"`
	PageInfo *CommonPageInfo `json:"pageInfo,omitempty"`
}

// NewV1SdkAutomationPlaybookConfigsGetResponse instantiates a new V1SdkAutomationPlaybookConfigsGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookConfigsGetResponse() *V1SdkAutomationPlaybookConfigsGetResponse {
	this := V1SdkAutomationPlaybookConfigsGetResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookConfigsGetResponseWithDefaults instantiates a new V1SdkAutomationPlaybookConfigsGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookConfigsGetResponseWithDefaults() *V1SdkAutomationPlaybookConfigsGetResponse {
	this := V1SdkAutomationPlaybookConfigsGetResponse{}
	return &this
}

// GetConfigs returns the Configs field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsGetResponse) GetConfigs() []SdkAutomationPlaybookConfigSummary {
	if o == nil || IsNil(o.Configs) {
		var ret []SdkAutomationPlaybookConfigSummary
		return ret
	}
	return o.Configs
}

// GetConfigsOk returns a tuple with the Configs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsGetResponse) GetConfigsOk() ([]SdkAutomationPlaybookConfigSummary, bool) {
	if o == nil || IsNil(o.Configs) {
		return nil, false
	}
	return o.Configs, true
}

// HasConfigs returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsGetResponse) HasConfigs() bool {
	if o != nil && !IsNil(o.Configs) {
		return true
	}

	return false
}

// SetConfigs gets a reference to the given []SdkAutomationPlaybookConfigSummary and assigns it to the Configs field.
func (o *V1SdkAutomationPlaybookConfigsGetResponse) SetConfigs(v []SdkAutomationPlaybookConfigSummary) {
	o.Configs = v
}

// GetPageInfo returns the PageInfo field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsGetResponse) GetPageInfo() CommonPageInfo {
	if o == nil || IsNil(o.PageInfo) {
		var ret CommonPageInfo
		return ret
	}
	return *o.PageInfo
}

// GetPageInfoOk returns a tuple with the PageInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsGetResponse) GetPageInfoOk() (*CommonPageInfo, bool) {
	if o == nil || IsNil(o.PageInfo) {
		return nil, false
	}
	return o.PageInfo, true
}

// HasPageInfo returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsGetResponse) HasPageInfo() bool {
	if o != nil && !IsNil(o.PageInfo) {
		return true
	}

	return false
}

// SetPageInfo gets a reference to the given CommonPageInfo and assigns it to the PageInfo field.
func (o *V1SdkAutomationPlaybookConfigsGetResponse) SetPageInfo(v CommonPageInfo) {
	o.PageInfo = &v
}

func (o V1SdkAutomationPlaybookConfigsGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookConfigsGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Configs) {
		toSerialize["configs"] = o.Configs
	}
	if !IsNil(o.PageInfo) {
		toSerialize["pageInfo"] = o.PageInfo
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookConfigsGetResponse struct {
	value *V1SdkAutomationPlaybookConfigsGetResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookConfigsGetResponse) Get() *V1SdkAutomationPlaybookConfigsGetResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookConfigsGetResponse) Set(val *V1SdkAutomationPlaybookConfigsGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookConfigsGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookConfigsGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookConfigsGetResponse(val *V1SdkAutomationPlaybookConfigsGetResponse) *NullableV1SdkAutomationPlaybookConfigsGetResponse {
	return &NullableV1SdkAutomationPlaybookConfigsGetResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookConfigsGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookConfigsGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


