/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the StatsmonV2FecRxStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsmonV2FecRxStats{}

// StatsmonV2FecRxStats struct for StatsmonV2FecRxStats
type StatsmonV2FecRxStats struct {
	ErasureRecoveredPackets *int64 `json:"erasureRecoveredPackets,omitempty"`
	ErasureUnrepairablePackets *int64 `json:"erasureUnrepairablePackets,omitempty"`
	RepairLevel *float32 `json:"repairLevel,omitempty"`
	RepairPackets *int64 `json:"repairPackets,omitempty"`
}

// NewStatsmonV2FecRxStats instantiates a new StatsmonV2FecRxStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsmonV2FecRxStats() *StatsmonV2FecRxStats {
	this := StatsmonV2FecRxStats{}
	return &this
}

// NewStatsmonV2FecRxStatsWithDefaults instantiates a new StatsmonV2FecRxStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsmonV2FecRxStatsWithDefaults() *StatsmonV2FecRxStats {
	this := StatsmonV2FecRxStats{}
	return &this
}

// GetErasureRecoveredPackets returns the ErasureRecoveredPackets field value if set, zero value otherwise.
func (o *StatsmonV2FecRxStats) GetErasureRecoveredPackets() int64 {
	if o == nil || IsNil(o.ErasureRecoveredPackets) {
		var ret int64
		return ret
	}
	return *o.ErasureRecoveredPackets
}

// GetErasureRecoveredPacketsOk returns a tuple with the ErasureRecoveredPackets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2FecRxStats) GetErasureRecoveredPacketsOk() (*int64, bool) {
	if o == nil || IsNil(o.ErasureRecoveredPackets) {
		return nil, false
	}
	return o.ErasureRecoveredPackets, true
}

// HasErasureRecoveredPackets returns a boolean if a field has been set.
func (o *StatsmonV2FecRxStats) HasErasureRecoveredPackets() bool {
	if o != nil && !IsNil(o.ErasureRecoveredPackets) {
		return true
	}

	return false
}

// SetErasureRecoveredPackets gets a reference to the given int64 and assigns it to the ErasureRecoveredPackets field.
func (o *StatsmonV2FecRxStats) SetErasureRecoveredPackets(v int64) {
	o.ErasureRecoveredPackets = &v
}

// GetErasureUnrepairablePackets returns the ErasureUnrepairablePackets field value if set, zero value otherwise.
func (o *StatsmonV2FecRxStats) GetErasureUnrepairablePackets() int64 {
	if o == nil || IsNil(o.ErasureUnrepairablePackets) {
		var ret int64
		return ret
	}
	return *o.ErasureUnrepairablePackets
}

// GetErasureUnrepairablePacketsOk returns a tuple with the ErasureUnrepairablePackets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2FecRxStats) GetErasureUnrepairablePacketsOk() (*int64, bool) {
	if o == nil || IsNil(o.ErasureUnrepairablePackets) {
		return nil, false
	}
	return o.ErasureUnrepairablePackets, true
}

// HasErasureUnrepairablePackets returns a boolean if a field has been set.
func (o *StatsmonV2FecRxStats) HasErasureUnrepairablePackets() bool {
	if o != nil && !IsNil(o.ErasureUnrepairablePackets) {
		return true
	}

	return false
}

// SetErasureUnrepairablePackets gets a reference to the given int64 and assigns it to the ErasureUnrepairablePackets field.
func (o *StatsmonV2FecRxStats) SetErasureUnrepairablePackets(v int64) {
	o.ErasureUnrepairablePackets = &v
}

// GetRepairLevel returns the RepairLevel field value if set, zero value otherwise.
func (o *StatsmonV2FecRxStats) GetRepairLevel() float32 {
	if o == nil || IsNil(o.RepairLevel) {
		var ret float32
		return ret
	}
	return *o.RepairLevel
}

// GetRepairLevelOk returns a tuple with the RepairLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2FecRxStats) GetRepairLevelOk() (*float32, bool) {
	if o == nil || IsNil(o.RepairLevel) {
		return nil, false
	}
	return o.RepairLevel, true
}

// HasRepairLevel returns a boolean if a field has been set.
func (o *StatsmonV2FecRxStats) HasRepairLevel() bool {
	if o != nil && !IsNil(o.RepairLevel) {
		return true
	}

	return false
}

// SetRepairLevel gets a reference to the given float32 and assigns it to the RepairLevel field.
func (o *StatsmonV2FecRxStats) SetRepairLevel(v float32) {
	o.RepairLevel = &v
}

// GetRepairPackets returns the RepairPackets field value if set, zero value otherwise.
func (o *StatsmonV2FecRxStats) GetRepairPackets() int64 {
	if o == nil || IsNil(o.RepairPackets) {
		var ret int64
		return ret
	}
	return *o.RepairPackets
}

// GetRepairPacketsOk returns a tuple with the RepairPackets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatsmonV2FecRxStats) GetRepairPacketsOk() (*int64, bool) {
	if o == nil || IsNil(o.RepairPackets) {
		return nil, false
	}
	return o.RepairPackets, true
}

// HasRepairPackets returns a boolean if a field has been set.
func (o *StatsmonV2FecRxStats) HasRepairPackets() bool {
	if o != nil && !IsNil(o.RepairPackets) {
		return true
	}

	return false
}

// SetRepairPackets gets a reference to the given int64 and assigns it to the RepairPackets field.
func (o *StatsmonV2FecRxStats) SetRepairPackets(v int64) {
	o.RepairPackets = &v
}

func (o StatsmonV2FecRxStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsmonV2FecRxStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErasureRecoveredPackets) {
		toSerialize["erasureRecoveredPackets"] = o.ErasureRecoveredPackets
	}
	if !IsNil(o.ErasureUnrepairablePackets) {
		toSerialize["erasureUnrepairablePackets"] = o.ErasureUnrepairablePackets
	}
	if !IsNil(o.RepairLevel) {
		toSerialize["repairLevel"] = o.RepairLevel
	}
	if !IsNil(o.RepairPackets) {
		toSerialize["repairPackets"] = o.RepairPackets
	}
	return toSerialize, nil
}

type NullableStatsmonV2FecRxStats struct {
	value *StatsmonV2FecRxStats
	isSet bool
}

func (v NullableStatsmonV2FecRxStats) Get() *StatsmonV2FecRxStats {
	return v.value
}

func (v *NullableStatsmonV2FecRxStats) Set(val *StatsmonV2FecRxStats) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsmonV2FecRxStats) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsmonV2FecRxStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsmonV2FecRxStats(val *StatsmonV2FecRxStats) *NullableStatsmonV2FecRxStats {
	return &NullableStatsmonV2FecRxStats{value: val, isSet: true}
}

func (v NullableStatsmonV2FecRxStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsmonV2FecRxStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


