/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookModuleSlotsGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookModuleSlotsGetResponse{}

// V1SdkAutomationPlaybookModuleSlotsGetResponse struct for V1SdkAutomationPlaybookModuleSlotsGetResponse
type V1SdkAutomationPlaybookModuleSlotsGetResponse struct {
	Modules []SdkAutomationCatalogModuleSlot `json:"modules,omitempty"`
}

// NewV1SdkAutomationPlaybookModuleSlotsGetResponse instantiates a new V1SdkAutomationPlaybookModuleSlotsGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookModuleSlotsGetResponse() *V1SdkAutomationPlaybookModuleSlotsGetResponse {
	this := V1SdkAutomationPlaybookModuleSlotsGetResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookModuleSlotsGetResponseWithDefaults instantiates a new V1SdkAutomationPlaybookModuleSlotsGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookModuleSlotsGetResponseWithDefaults() *V1SdkAutomationPlaybookModuleSlotsGetResponse {
	this := V1SdkAutomationPlaybookModuleSlotsGetResponse{}
	return &this
}

// GetModules returns the Modules field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookModuleSlotsGetResponse) GetModules() []SdkAutomationCatalogModuleSlot {
	if o == nil || IsNil(o.Modules) {
		var ret []SdkAutomationCatalogModuleSlot
		return ret
	}
	return o.Modules
}

// GetModulesOk returns a tuple with the Modules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookModuleSlotsGetResponse) GetModulesOk() ([]SdkAutomationCatalogModuleSlot, bool) {
	if o == nil || IsNil(o.Modules) {
		return nil, false
	}
	return o.Modules, true
}

// HasModules returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookModuleSlotsGetResponse) HasModules() bool {
	if o != nil && !IsNil(o.Modules) {
		return true
	}

	return false
}

// SetModules gets a reference to the given []SdkAutomationCatalogModuleSlot and assigns it to the Modules field.
func (o *V1SdkAutomationPlaybookModuleSlotsGetResponse) SetModules(v []SdkAutomationCatalogModuleSlot) {
	o.Modules = v
}

func (o V1SdkAutomationPlaybookModuleSlotsGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookModuleSlotsGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Modules) {
		toSerialize["modules"] = o.Modules
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookModuleSlotsGetResponse struct {
	value *V1SdkAutomationPlaybookModuleSlotsGetResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookModuleSlotsGetResponse) Get() *V1SdkAutomationPlaybookModuleSlotsGetResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookModuleSlotsGetResponse) Set(val *V1SdkAutomationPlaybookModuleSlotsGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookModuleSlotsGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookModuleSlotsGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookModuleSlotsGetResponse(val *V1SdkAutomationPlaybookModuleSlotsGetResponse) *NullableV1SdkAutomationPlaybookModuleSlotsGetResponse {
	return &NullableV1SdkAutomationPlaybookModuleSlotsGetResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookModuleSlotsGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookModuleSlotsGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


