/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the SdkAutomationPlaybookJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SdkAutomationPlaybookJob{}

// SdkAutomationPlaybookJob struct for SdkAutomationPlaybookJob
type SdkAutomationPlaybookJob struct {
	// graphiant.naas collection version used for this run
	CollectionVersion *string `json:"collectionVersion,omitempty"`
	// Config description / notes frozen at job creation (from config_snapshot); empty for older jobs
	ConfigDescription *string `json:"configDescription,omitempty"`
	// Owning playbook config id
	ConfigId *string `json:"configId,omitempty"`
	// Config display name frozen at job creation (from config_snapshot); empty for older jobs
	ConfigName *string `json:"configName,omitempty"`
	DeployEndedAt *GoogleProtobufTimestamp `json:"deployEndedAt,omitempty"`
	DeployStartedAt *GoogleProtobufTimestamp `json:"deployStartedAt,omitempty"`
	DryRunEndedAt *GoogleProtobufTimestamp `json:"dryRunEndedAt,omitempty"`
	DryRunStartedAt *GoogleProtobufTimestamp `json:"dryRunStartedAt,omitempty"`
	// When status is FAILED, which phase failed; unset when not failed
	FailedPhase *string `json:"failedPhase,omitempty"`
	// Unique id of this playbook job run
	JobId *string `json:"jobId,omitempty"`
	// True when ansible logs are available for this run
	LogsAvailable *bool `json:"logsAvailable,omitempty"`
	PostDeployCheckStartedAt *GoogleProtobufTimestamp `json:"postDeployCheckStartedAt,omitempty"`
	// Wall-clock duration in milliseconds from dry_run_started_at to run_ended_at; unset until run_ended_at is set
	RunDurationMs *int64 `json:"runDurationMs,omitempty"`
	RunEndedAt *GoogleProtobufTimestamp `json:"runEndedAt,omitempty"`
	// Per-config run counter (1-based for started runs)
	RunNumber *int32 `json:"runNumber,omitempty"`
	// External ansible runner job id, if the backend assigned one
	RunnerJobId *string `json:"runnerJobId,omitempty"`
	// SDK version used for this run
	SdkVersion *string `json:"sdkVersion,omitempty"`
	// IAM UserInfo.user_id of who started this run; UI resolves the display name
	StartedByUserId *string `json:"startedByUserId,omitempty"`
	// Gated pipeline state (dry-run / deploy / post-deploy-check)
	Status *string `json:"status,omitempty"`
	// Whether ansible -vvv was requested for the latest phase of this run
	VerboseLogs *bool `json:"verboseLogs,omitempty"`
}

// NewSdkAutomationPlaybookJob instantiates a new SdkAutomationPlaybookJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSdkAutomationPlaybookJob() *SdkAutomationPlaybookJob {
	this := SdkAutomationPlaybookJob{}
	return &this
}

// NewSdkAutomationPlaybookJobWithDefaults instantiates a new SdkAutomationPlaybookJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSdkAutomationPlaybookJobWithDefaults() *SdkAutomationPlaybookJob {
	this := SdkAutomationPlaybookJob{}
	return &this
}

// GetCollectionVersion returns the CollectionVersion field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetCollectionVersion() string {
	if o == nil || IsNil(o.CollectionVersion) {
		var ret string
		return ret
	}
	return *o.CollectionVersion
}

// GetCollectionVersionOk returns a tuple with the CollectionVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetCollectionVersionOk() (*string, bool) {
	if o == nil || IsNil(o.CollectionVersion) {
		return nil, false
	}
	return o.CollectionVersion, true
}

// HasCollectionVersion returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasCollectionVersion() bool {
	if o != nil && !IsNil(o.CollectionVersion) {
		return true
	}

	return false
}

// SetCollectionVersion gets a reference to the given string and assigns it to the CollectionVersion field.
func (o *SdkAutomationPlaybookJob) SetCollectionVersion(v string) {
	o.CollectionVersion = &v
}

// GetConfigDescription returns the ConfigDescription field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetConfigDescription() string {
	if o == nil || IsNil(o.ConfigDescription) {
		var ret string
		return ret
	}
	return *o.ConfigDescription
}

// GetConfigDescriptionOk returns a tuple with the ConfigDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetConfigDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.ConfigDescription) {
		return nil, false
	}
	return o.ConfigDescription, true
}

// HasConfigDescription returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasConfigDescription() bool {
	if o != nil && !IsNil(o.ConfigDescription) {
		return true
	}

	return false
}

// SetConfigDescription gets a reference to the given string and assigns it to the ConfigDescription field.
func (o *SdkAutomationPlaybookJob) SetConfigDescription(v string) {
	o.ConfigDescription = &v
}

// GetConfigId returns the ConfigId field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetConfigId() string {
	if o == nil || IsNil(o.ConfigId) {
		var ret string
		return ret
	}
	return *o.ConfigId
}

// GetConfigIdOk returns a tuple with the ConfigId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetConfigIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConfigId) {
		return nil, false
	}
	return o.ConfigId, true
}

// HasConfigId returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasConfigId() bool {
	if o != nil && !IsNil(o.ConfigId) {
		return true
	}

	return false
}

// SetConfigId gets a reference to the given string and assigns it to the ConfigId field.
func (o *SdkAutomationPlaybookJob) SetConfigId(v string) {
	o.ConfigId = &v
}

// GetConfigName returns the ConfigName field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetConfigName() string {
	if o == nil || IsNil(o.ConfigName) {
		var ret string
		return ret
	}
	return *o.ConfigName
}

// GetConfigNameOk returns a tuple with the ConfigName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetConfigNameOk() (*string, bool) {
	if o == nil || IsNil(o.ConfigName) {
		return nil, false
	}
	return o.ConfigName, true
}

// HasConfigName returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasConfigName() bool {
	if o != nil && !IsNil(o.ConfigName) {
		return true
	}

	return false
}

// SetConfigName gets a reference to the given string and assigns it to the ConfigName field.
func (o *SdkAutomationPlaybookJob) SetConfigName(v string) {
	o.ConfigName = &v
}

// GetDeployEndedAt returns the DeployEndedAt field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetDeployEndedAt() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.DeployEndedAt) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.DeployEndedAt
}

// GetDeployEndedAtOk returns a tuple with the DeployEndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetDeployEndedAtOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.DeployEndedAt) {
		return nil, false
	}
	return o.DeployEndedAt, true
}

// HasDeployEndedAt returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasDeployEndedAt() bool {
	if o != nil && !IsNil(o.DeployEndedAt) {
		return true
	}

	return false
}

// SetDeployEndedAt gets a reference to the given GoogleProtobufTimestamp and assigns it to the DeployEndedAt field.
func (o *SdkAutomationPlaybookJob) SetDeployEndedAt(v GoogleProtobufTimestamp) {
	o.DeployEndedAt = &v
}

// GetDeployStartedAt returns the DeployStartedAt field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetDeployStartedAt() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.DeployStartedAt) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.DeployStartedAt
}

// GetDeployStartedAtOk returns a tuple with the DeployStartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetDeployStartedAtOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.DeployStartedAt) {
		return nil, false
	}
	return o.DeployStartedAt, true
}

// HasDeployStartedAt returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasDeployStartedAt() bool {
	if o != nil && !IsNil(o.DeployStartedAt) {
		return true
	}

	return false
}

// SetDeployStartedAt gets a reference to the given GoogleProtobufTimestamp and assigns it to the DeployStartedAt field.
func (o *SdkAutomationPlaybookJob) SetDeployStartedAt(v GoogleProtobufTimestamp) {
	o.DeployStartedAt = &v
}

// GetDryRunEndedAt returns the DryRunEndedAt field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetDryRunEndedAt() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.DryRunEndedAt) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.DryRunEndedAt
}

// GetDryRunEndedAtOk returns a tuple with the DryRunEndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetDryRunEndedAtOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.DryRunEndedAt) {
		return nil, false
	}
	return o.DryRunEndedAt, true
}

// HasDryRunEndedAt returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasDryRunEndedAt() bool {
	if o != nil && !IsNil(o.DryRunEndedAt) {
		return true
	}

	return false
}

// SetDryRunEndedAt gets a reference to the given GoogleProtobufTimestamp and assigns it to the DryRunEndedAt field.
func (o *SdkAutomationPlaybookJob) SetDryRunEndedAt(v GoogleProtobufTimestamp) {
	o.DryRunEndedAt = &v
}

// GetDryRunStartedAt returns the DryRunStartedAt field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetDryRunStartedAt() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.DryRunStartedAt) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.DryRunStartedAt
}

// GetDryRunStartedAtOk returns a tuple with the DryRunStartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetDryRunStartedAtOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.DryRunStartedAt) {
		return nil, false
	}
	return o.DryRunStartedAt, true
}

// HasDryRunStartedAt returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasDryRunStartedAt() bool {
	if o != nil && !IsNil(o.DryRunStartedAt) {
		return true
	}

	return false
}

// SetDryRunStartedAt gets a reference to the given GoogleProtobufTimestamp and assigns it to the DryRunStartedAt field.
func (o *SdkAutomationPlaybookJob) SetDryRunStartedAt(v GoogleProtobufTimestamp) {
	o.DryRunStartedAt = &v
}

// GetFailedPhase returns the FailedPhase field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetFailedPhase() string {
	if o == nil || IsNil(o.FailedPhase) {
		var ret string
		return ret
	}
	return *o.FailedPhase
}

// GetFailedPhaseOk returns a tuple with the FailedPhase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetFailedPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.FailedPhase) {
		return nil, false
	}
	return o.FailedPhase, true
}

// HasFailedPhase returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasFailedPhase() bool {
	if o != nil && !IsNil(o.FailedPhase) {
		return true
	}

	return false
}

// SetFailedPhase gets a reference to the given string and assigns it to the FailedPhase field.
func (o *SdkAutomationPlaybookJob) SetFailedPhase(v string) {
	o.FailedPhase = &v
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *SdkAutomationPlaybookJob) SetJobId(v string) {
	o.JobId = &v
}

// GetLogsAvailable returns the LogsAvailable field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetLogsAvailable() bool {
	if o == nil || IsNil(o.LogsAvailable) {
		var ret bool
		return ret
	}
	return *o.LogsAvailable
}

// GetLogsAvailableOk returns a tuple with the LogsAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetLogsAvailableOk() (*bool, bool) {
	if o == nil || IsNil(o.LogsAvailable) {
		return nil, false
	}
	return o.LogsAvailable, true
}

// HasLogsAvailable returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasLogsAvailable() bool {
	if o != nil && !IsNil(o.LogsAvailable) {
		return true
	}

	return false
}

// SetLogsAvailable gets a reference to the given bool and assigns it to the LogsAvailable field.
func (o *SdkAutomationPlaybookJob) SetLogsAvailable(v bool) {
	o.LogsAvailable = &v
}

// GetPostDeployCheckStartedAt returns the PostDeployCheckStartedAt field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetPostDeployCheckStartedAt() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.PostDeployCheckStartedAt) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.PostDeployCheckStartedAt
}

// GetPostDeployCheckStartedAtOk returns a tuple with the PostDeployCheckStartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetPostDeployCheckStartedAtOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.PostDeployCheckStartedAt) {
		return nil, false
	}
	return o.PostDeployCheckStartedAt, true
}

// HasPostDeployCheckStartedAt returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasPostDeployCheckStartedAt() bool {
	if o != nil && !IsNil(o.PostDeployCheckStartedAt) {
		return true
	}

	return false
}

// SetPostDeployCheckStartedAt gets a reference to the given GoogleProtobufTimestamp and assigns it to the PostDeployCheckStartedAt field.
func (o *SdkAutomationPlaybookJob) SetPostDeployCheckStartedAt(v GoogleProtobufTimestamp) {
	o.PostDeployCheckStartedAt = &v
}

// GetRunDurationMs returns the RunDurationMs field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetRunDurationMs() int64 {
	if o == nil || IsNil(o.RunDurationMs) {
		var ret int64
		return ret
	}
	return *o.RunDurationMs
}

// GetRunDurationMsOk returns a tuple with the RunDurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetRunDurationMsOk() (*int64, bool) {
	if o == nil || IsNil(o.RunDurationMs) {
		return nil, false
	}
	return o.RunDurationMs, true
}

// HasRunDurationMs returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasRunDurationMs() bool {
	if o != nil && !IsNil(o.RunDurationMs) {
		return true
	}

	return false
}

// SetRunDurationMs gets a reference to the given int64 and assigns it to the RunDurationMs field.
func (o *SdkAutomationPlaybookJob) SetRunDurationMs(v int64) {
	o.RunDurationMs = &v
}

// GetRunEndedAt returns the RunEndedAt field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetRunEndedAt() GoogleProtobufTimestamp {
	if o == nil || IsNil(o.RunEndedAt) {
		var ret GoogleProtobufTimestamp
		return ret
	}
	return *o.RunEndedAt
}

// GetRunEndedAtOk returns a tuple with the RunEndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetRunEndedAtOk() (*GoogleProtobufTimestamp, bool) {
	if o == nil || IsNil(o.RunEndedAt) {
		return nil, false
	}
	return o.RunEndedAt, true
}

// HasRunEndedAt returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasRunEndedAt() bool {
	if o != nil && !IsNil(o.RunEndedAt) {
		return true
	}

	return false
}

// SetRunEndedAt gets a reference to the given GoogleProtobufTimestamp and assigns it to the RunEndedAt field.
func (o *SdkAutomationPlaybookJob) SetRunEndedAt(v GoogleProtobufTimestamp) {
	o.RunEndedAt = &v
}

// GetRunNumber returns the RunNumber field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetRunNumber() int32 {
	if o == nil || IsNil(o.RunNumber) {
		var ret int32
		return ret
	}
	return *o.RunNumber
}

// GetRunNumberOk returns a tuple with the RunNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetRunNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.RunNumber) {
		return nil, false
	}
	return o.RunNumber, true
}

// HasRunNumber returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasRunNumber() bool {
	if o != nil && !IsNil(o.RunNumber) {
		return true
	}

	return false
}

// SetRunNumber gets a reference to the given int32 and assigns it to the RunNumber field.
func (o *SdkAutomationPlaybookJob) SetRunNumber(v int32) {
	o.RunNumber = &v
}

// GetRunnerJobId returns the RunnerJobId field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetRunnerJobId() string {
	if o == nil || IsNil(o.RunnerJobId) {
		var ret string
		return ret
	}
	return *o.RunnerJobId
}

// GetRunnerJobIdOk returns a tuple with the RunnerJobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetRunnerJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.RunnerJobId) {
		return nil, false
	}
	return o.RunnerJobId, true
}

// HasRunnerJobId returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasRunnerJobId() bool {
	if o != nil && !IsNil(o.RunnerJobId) {
		return true
	}

	return false
}

// SetRunnerJobId gets a reference to the given string and assigns it to the RunnerJobId field.
func (o *SdkAutomationPlaybookJob) SetRunnerJobId(v string) {
	o.RunnerJobId = &v
}

// GetSdkVersion returns the SdkVersion field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetSdkVersion() string {
	if o == nil || IsNil(o.SdkVersion) {
		var ret string
		return ret
	}
	return *o.SdkVersion
}

// GetSdkVersionOk returns a tuple with the SdkVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetSdkVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SdkVersion) {
		return nil, false
	}
	return o.SdkVersion, true
}

// HasSdkVersion returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasSdkVersion() bool {
	if o != nil && !IsNil(o.SdkVersion) {
		return true
	}

	return false
}

// SetSdkVersion gets a reference to the given string and assigns it to the SdkVersion field.
func (o *SdkAutomationPlaybookJob) SetSdkVersion(v string) {
	o.SdkVersion = &v
}

// GetStartedByUserId returns the StartedByUserId field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetStartedByUserId() string {
	if o == nil || IsNil(o.StartedByUserId) {
		var ret string
		return ret
	}
	return *o.StartedByUserId
}

// GetStartedByUserIdOk returns a tuple with the StartedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetStartedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.StartedByUserId) {
		return nil, false
	}
	return o.StartedByUserId, true
}

// HasStartedByUserId returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasStartedByUserId() bool {
	if o != nil && !IsNil(o.StartedByUserId) {
		return true
	}

	return false
}

// SetStartedByUserId gets a reference to the given string and assigns it to the StartedByUserId field.
func (o *SdkAutomationPlaybookJob) SetStartedByUserId(v string) {
	o.StartedByUserId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *SdkAutomationPlaybookJob) SetStatus(v string) {
	o.Status = &v
}

// GetVerboseLogs returns the VerboseLogs field value if set, zero value otherwise.
func (o *SdkAutomationPlaybookJob) GetVerboseLogs() bool {
	if o == nil || IsNil(o.VerboseLogs) {
		var ret bool
		return ret
	}
	return *o.VerboseLogs
}

// GetVerboseLogsOk returns a tuple with the VerboseLogs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SdkAutomationPlaybookJob) GetVerboseLogsOk() (*bool, bool) {
	if o == nil || IsNil(o.VerboseLogs) {
		return nil, false
	}
	return o.VerboseLogs, true
}

// HasVerboseLogs returns a boolean if a field has been set.
func (o *SdkAutomationPlaybookJob) HasVerboseLogs() bool {
	if o != nil && !IsNil(o.VerboseLogs) {
		return true
	}

	return false
}

// SetVerboseLogs gets a reference to the given bool and assigns it to the VerboseLogs field.
func (o *SdkAutomationPlaybookJob) SetVerboseLogs(v bool) {
	o.VerboseLogs = &v
}

func (o SdkAutomationPlaybookJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SdkAutomationPlaybookJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CollectionVersion) {
		toSerialize["collectionVersion"] = o.CollectionVersion
	}
	if !IsNil(o.ConfigDescription) {
		toSerialize["configDescription"] = o.ConfigDescription
	}
	if !IsNil(o.ConfigId) {
		toSerialize["configId"] = o.ConfigId
	}
	if !IsNil(o.ConfigName) {
		toSerialize["configName"] = o.ConfigName
	}
	if !IsNil(o.DeployEndedAt) {
		toSerialize["deployEndedAt"] = o.DeployEndedAt
	}
	if !IsNil(o.DeployStartedAt) {
		toSerialize["deployStartedAt"] = o.DeployStartedAt
	}
	if !IsNil(o.DryRunEndedAt) {
		toSerialize["dryRunEndedAt"] = o.DryRunEndedAt
	}
	if !IsNil(o.DryRunStartedAt) {
		toSerialize["dryRunStartedAt"] = o.DryRunStartedAt
	}
	if !IsNil(o.FailedPhase) {
		toSerialize["failedPhase"] = o.FailedPhase
	}
	if !IsNil(o.JobId) {
		toSerialize["jobId"] = o.JobId
	}
	if !IsNil(o.LogsAvailable) {
		toSerialize["logsAvailable"] = o.LogsAvailable
	}
	if !IsNil(o.PostDeployCheckStartedAt) {
		toSerialize["postDeployCheckStartedAt"] = o.PostDeployCheckStartedAt
	}
	if !IsNil(o.RunDurationMs) {
		toSerialize["runDurationMs"] = o.RunDurationMs
	}
	if !IsNil(o.RunEndedAt) {
		toSerialize["runEndedAt"] = o.RunEndedAt
	}
	if !IsNil(o.RunNumber) {
		toSerialize["runNumber"] = o.RunNumber
	}
	if !IsNil(o.RunnerJobId) {
		toSerialize["runnerJobId"] = o.RunnerJobId
	}
	if !IsNil(o.SdkVersion) {
		toSerialize["sdkVersion"] = o.SdkVersion
	}
	if !IsNil(o.StartedByUserId) {
		toSerialize["startedByUserId"] = o.StartedByUserId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.VerboseLogs) {
		toSerialize["verboseLogs"] = o.VerboseLogs
	}
	return toSerialize, nil
}

type NullableSdkAutomationPlaybookJob struct {
	value *SdkAutomationPlaybookJob
	isSet bool
}

func (v NullableSdkAutomationPlaybookJob) Get() *SdkAutomationPlaybookJob {
	return v.value
}

func (v *NullableSdkAutomationPlaybookJob) Set(val *SdkAutomationPlaybookJob) {
	v.value = val
	v.isSet = true
}

func (v NullableSdkAutomationPlaybookJob) IsSet() bool {
	return v.isSet
}

func (v *NullableSdkAutomationPlaybookJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSdkAutomationPlaybookJob(val *SdkAutomationPlaybookJob) *NullableSdkAutomationPlaybookJob {
	return &NullableSdkAutomationPlaybookJob{value: val, isSet: true}
}

func (v NullableSdkAutomationPlaybookJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSdkAutomationPlaybookJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


