/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookTemplatesGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookTemplatesGetResponse{}

// V1SdkAutomationPlaybookTemplatesGetResponse struct for V1SdkAutomationPlaybookTemplatesGetResponse
type V1SdkAutomationPlaybookTemplatesGetResponse struct {
	// graphiant.naas collection version the files were read from
	CollectionVersion *string `json:"collectionVersion,omitempty"`
	Files []SdkAutomationTemplateFile `json:"files,omitempty"`
}

// NewV1SdkAutomationPlaybookTemplatesGetResponse instantiates a new V1SdkAutomationPlaybookTemplatesGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookTemplatesGetResponse() *V1SdkAutomationPlaybookTemplatesGetResponse {
	this := V1SdkAutomationPlaybookTemplatesGetResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookTemplatesGetResponseWithDefaults instantiates a new V1SdkAutomationPlaybookTemplatesGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookTemplatesGetResponseWithDefaults() *V1SdkAutomationPlaybookTemplatesGetResponse {
	this := V1SdkAutomationPlaybookTemplatesGetResponse{}
	return &this
}

// GetCollectionVersion returns the CollectionVersion field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookTemplatesGetResponse) GetCollectionVersion() string {
	if o == nil || IsNil(o.CollectionVersion) {
		var ret string
		return ret
	}
	return *o.CollectionVersion
}

// GetCollectionVersionOk returns a tuple with the CollectionVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookTemplatesGetResponse) GetCollectionVersionOk() (*string, bool) {
	if o == nil || IsNil(o.CollectionVersion) {
		return nil, false
	}
	return o.CollectionVersion, true
}

// HasCollectionVersion returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookTemplatesGetResponse) HasCollectionVersion() bool {
	if o != nil && !IsNil(o.CollectionVersion) {
		return true
	}

	return false
}

// SetCollectionVersion gets a reference to the given string and assigns it to the CollectionVersion field.
func (o *V1SdkAutomationPlaybookTemplatesGetResponse) SetCollectionVersion(v string) {
	o.CollectionVersion = &v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookTemplatesGetResponse) GetFiles() []SdkAutomationTemplateFile {
	if o == nil || IsNil(o.Files) {
		var ret []SdkAutomationTemplateFile
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookTemplatesGetResponse) GetFilesOk() ([]SdkAutomationTemplateFile, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookTemplatesGetResponse) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []SdkAutomationTemplateFile and assigns it to the Files field.
func (o *V1SdkAutomationPlaybookTemplatesGetResponse) SetFiles(v []SdkAutomationTemplateFile) {
	o.Files = v
}

func (o V1SdkAutomationPlaybookTemplatesGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookTemplatesGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CollectionVersion) {
		toSerialize["collectionVersion"] = o.CollectionVersion
	}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookTemplatesGetResponse struct {
	value *V1SdkAutomationPlaybookTemplatesGetResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookTemplatesGetResponse) Get() *V1SdkAutomationPlaybookTemplatesGetResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookTemplatesGetResponse) Set(val *V1SdkAutomationPlaybookTemplatesGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookTemplatesGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookTemplatesGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookTemplatesGetResponse(val *V1SdkAutomationPlaybookTemplatesGetResponse) *NullableV1SdkAutomationPlaybookTemplatesGetResponse {
	return &NullableV1SdkAutomationPlaybookTemplatesGetResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookTemplatesGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookTemplatesGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


