/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookJobsJobIdResumePostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookJobsJobIdResumePostResponse{}

// V1SdkAutomationPlaybookJobsJobIdResumePostResponse struct for V1SdkAutomationPlaybookJobsJobIdResumePostResponse
type V1SdkAutomationPlaybookJobsJobIdResumePostResponse struct {
	// Resumed job id
	JobId *string `json:"jobId,omitempty"`
	// Job status after resume was accepted
	Status *string `json:"status,omitempty"`
}

// NewV1SdkAutomationPlaybookJobsJobIdResumePostResponse instantiates a new V1SdkAutomationPlaybookJobsJobIdResumePostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookJobsJobIdResumePostResponse() *V1SdkAutomationPlaybookJobsJobIdResumePostResponse {
	this := V1SdkAutomationPlaybookJobsJobIdResumePostResponse{}
	return &this
}

// NewV1SdkAutomationPlaybookJobsJobIdResumePostResponseWithDefaults instantiates a new V1SdkAutomationPlaybookJobsJobIdResumePostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookJobsJobIdResumePostResponseWithDefaults() *V1SdkAutomationPlaybookJobsJobIdResumePostResponse {
	this := V1SdkAutomationPlaybookJobsJobIdResumePostResponse{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostResponse) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostResponse) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostResponse) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostResponse) SetJobId(v string) {
	o.JobId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *V1SdkAutomationPlaybookJobsJobIdResumePostResponse) SetStatus(v string) {
	o.Status = &v
}

func (o V1SdkAutomationPlaybookJobsJobIdResumePostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookJobsJobIdResumePostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JobId) {
		toSerialize["jobId"] = o.JobId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookJobsJobIdResumePostResponse struct {
	value *V1SdkAutomationPlaybookJobsJobIdResumePostResponse
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdResumePostResponse) Get() *V1SdkAutomationPlaybookJobsJobIdResumePostResponse {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdResumePostResponse) Set(val *V1SdkAutomationPlaybookJobsJobIdResumePostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdResumePostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdResumePostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookJobsJobIdResumePostResponse(val *V1SdkAutomationPlaybookJobsJobIdResumePostResponse) *NullableV1SdkAutomationPlaybookJobsJobIdResumePostResponse {
	return &NullableV1SdkAutomationPlaybookJobsJobIdResumePostResponse{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdResumePostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdResumePostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


