/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1EnterprisesPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1EnterprisesPatchRequest{}

// V1EnterprisesPatchRequest struct for V1EnterprisesPatchRequest
type V1EnterprisesPatchRequest struct {
	AdminEmail *string `json:"adminEmail,omitempty"`
	BackboneApisEnabled *bool `json:"backboneApisEnabled,omitempty"`
	CloudProvider *string `json:"cloudProvider,omitempty"`
	CompanyName *string `json:"companyName,omitempty"`
	CreditLimit *int32 `json:"creditLimit,omitempty"`
	Description *string `json:"description,omitempty"`
	EnterpriseContract *CommonBillingContract `json:"enterpriseContract,omitempty"`
	//  (required)
	EnterpriseId int64 `json:"enterpriseId"`
	ImpersonationEnabled *bool `json:"impersonationEnabled,omitempty"`
	Logo *string `json:"logo,omitempty"`
	MarketplaceId *string `json:"marketplaceId,omitempty"`
	PortalBanner *string `json:"portalBanner,omitempty"`
	ProxyTenantId *int64 `json:"proxyTenantId,omitempty"`
	SmallLogo *string `json:"smallLogo,omitempty"`
	TokenExpiry *V1EnterprisesPatchRequestTokenExpiry `json:"tokenExpiry,omitempty"`
}

type _V1EnterprisesPatchRequest V1EnterprisesPatchRequest

// NewV1EnterprisesPatchRequest instantiates a new V1EnterprisesPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1EnterprisesPatchRequest(enterpriseId int64) *V1EnterprisesPatchRequest {
	this := V1EnterprisesPatchRequest{}
	this.EnterpriseId = enterpriseId
	return &this
}

// NewV1EnterprisesPatchRequestWithDefaults instantiates a new V1EnterprisesPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1EnterprisesPatchRequestWithDefaults() *V1EnterprisesPatchRequest {
	this := V1EnterprisesPatchRequest{}
	return &this
}

// GetAdminEmail returns the AdminEmail field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetAdminEmail() string {
	if o == nil || IsNil(o.AdminEmail) {
		var ret string
		return ret
	}
	return *o.AdminEmail
}

// GetAdminEmailOk returns a tuple with the AdminEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetAdminEmailOk() (*string, bool) {
	if o == nil || IsNil(o.AdminEmail) {
		return nil, false
	}
	return o.AdminEmail, true
}

// HasAdminEmail returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasAdminEmail() bool {
	if o != nil && !IsNil(o.AdminEmail) {
		return true
	}

	return false
}

// SetAdminEmail gets a reference to the given string and assigns it to the AdminEmail field.
func (o *V1EnterprisesPatchRequest) SetAdminEmail(v string) {
	o.AdminEmail = &v
}

// GetBackboneApisEnabled returns the BackboneApisEnabled field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetBackboneApisEnabled() bool {
	if o == nil || IsNil(o.BackboneApisEnabled) {
		var ret bool
		return ret
	}
	return *o.BackboneApisEnabled
}

// GetBackboneApisEnabledOk returns a tuple with the BackboneApisEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetBackboneApisEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.BackboneApisEnabled) {
		return nil, false
	}
	return o.BackboneApisEnabled, true
}

// HasBackboneApisEnabled returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasBackboneApisEnabled() bool {
	if o != nil && !IsNil(o.BackboneApisEnabled) {
		return true
	}

	return false
}

// SetBackboneApisEnabled gets a reference to the given bool and assigns it to the BackboneApisEnabled field.
func (o *V1EnterprisesPatchRequest) SetBackboneApisEnabled(v bool) {
	o.BackboneApisEnabled = &v
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetCloudProvider() string {
	if o == nil || IsNil(o.CloudProvider) {
		var ret string
		return ret
	}
	return *o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetCloudProviderOk() (*string, bool) {
	if o == nil || IsNil(o.CloudProvider) {
		return nil, false
	}
	return o.CloudProvider, true
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasCloudProvider() bool {
	if o != nil && !IsNil(o.CloudProvider) {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given string and assigns it to the CloudProvider field.
func (o *V1EnterprisesPatchRequest) SetCloudProvider(v string) {
	o.CloudProvider = &v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *V1EnterprisesPatchRequest) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetCreditLimit returns the CreditLimit field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetCreditLimit() int32 {
	if o == nil || IsNil(o.CreditLimit) {
		var ret int32
		return ret
	}
	return *o.CreditLimit
}

// GetCreditLimitOk returns a tuple with the CreditLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetCreditLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditLimit) {
		return nil, false
	}
	return o.CreditLimit, true
}

// HasCreditLimit returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasCreditLimit() bool {
	if o != nil && !IsNil(o.CreditLimit) {
		return true
	}

	return false
}

// SetCreditLimit gets a reference to the given int32 and assigns it to the CreditLimit field.
func (o *V1EnterprisesPatchRequest) SetCreditLimit(v int32) {
	o.CreditLimit = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *V1EnterprisesPatchRequest) SetDescription(v string) {
	o.Description = &v
}

// GetEnterpriseContract returns the EnterpriseContract field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetEnterpriseContract() CommonBillingContract {
	if o == nil || IsNil(o.EnterpriseContract) {
		var ret CommonBillingContract
		return ret
	}
	return *o.EnterpriseContract
}

// GetEnterpriseContractOk returns a tuple with the EnterpriseContract field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetEnterpriseContractOk() (*CommonBillingContract, bool) {
	if o == nil || IsNil(o.EnterpriseContract) {
		return nil, false
	}
	return o.EnterpriseContract, true
}

// HasEnterpriseContract returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasEnterpriseContract() bool {
	if o != nil && !IsNil(o.EnterpriseContract) {
		return true
	}

	return false
}

// SetEnterpriseContract gets a reference to the given CommonBillingContract and assigns it to the EnterpriseContract field.
func (o *V1EnterprisesPatchRequest) SetEnterpriseContract(v CommonBillingContract) {
	o.EnterpriseContract = &v
}

// GetEnterpriseId returns the EnterpriseId field value
func (o *V1EnterprisesPatchRequest) GetEnterpriseId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EnterpriseId
}

// GetEnterpriseIdOk returns a tuple with the EnterpriseId field value
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetEnterpriseIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnterpriseId, true
}

// SetEnterpriseId sets field value
func (o *V1EnterprisesPatchRequest) SetEnterpriseId(v int64) {
	o.EnterpriseId = v
}

// GetImpersonationEnabled returns the ImpersonationEnabled field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetImpersonationEnabled() bool {
	if o == nil || IsNil(o.ImpersonationEnabled) {
		var ret bool
		return ret
	}
	return *o.ImpersonationEnabled
}

// GetImpersonationEnabledOk returns a tuple with the ImpersonationEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetImpersonationEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ImpersonationEnabled) {
		return nil, false
	}
	return o.ImpersonationEnabled, true
}

// HasImpersonationEnabled returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasImpersonationEnabled() bool {
	if o != nil && !IsNil(o.ImpersonationEnabled) {
		return true
	}

	return false
}

// SetImpersonationEnabled gets a reference to the given bool and assigns it to the ImpersonationEnabled field.
func (o *V1EnterprisesPatchRequest) SetImpersonationEnabled(v bool) {
	o.ImpersonationEnabled = &v
}

// GetLogo returns the Logo field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetLogo() string {
	if o == nil || IsNil(o.Logo) {
		var ret string
		return ret
	}
	return *o.Logo
}

// GetLogoOk returns a tuple with the Logo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetLogoOk() (*string, bool) {
	if o == nil || IsNil(o.Logo) {
		return nil, false
	}
	return o.Logo, true
}

// HasLogo returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasLogo() bool {
	if o != nil && !IsNil(o.Logo) {
		return true
	}

	return false
}

// SetLogo gets a reference to the given string and assigns it to the Logo field.
func (o *V1EnterprisesPatchRequest) SetLogo(v string) {
	o.Logo = &v
}

// GetMarketplaceId returns the MarketplaceId field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetMarketplaceId() string {
	if o == nil || IsNil(o.MarketplaceId) {
		var ret string
		return ret
	}
	return *o.MarketplaceId
}

// GetMarketplaceIdOk returns a tuple with the MarketplaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetMarketplaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.MarketplaceId) {
		return nil, false
	}
	return o.MarketplaceId, true
}

// HasMarketplaceId returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasMarketplaceId() bool {
	if o != nil && !IsNil(o.MarketplaceId) {
		return true
	}

	return false
}

// SetMarketplaceId gets a reference to the given string and assigns it to the MarketplaceId field.
func (o *V1EnterprisesPatchRequest) SetMarketplaceId(v string) {
	o.MarketplaceId = &v
}

// GetPortalBanner returns the PortalBanner field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetPortalBanner() string {
	if o == nil || IsNil(o.PortalBanner) {
		var ret string
		return ret
	}
	return *o.PortalBanner
}

// GetPortalBannerOk returns a tuple with the PortalBanner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetPortalBannerOk() (*string, bool) {
	if o == nil || IsNil(o.PortalBanner) {
		return nil, false
	}
	return o.PortalBanner, true
}

// HasPortalBanner returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasPortalBanner() bool {
	if o != nil && !IsNil(o.PortalBanner) {
		return true
	}

	return false
}

// SetPortalBanner gets a reference to the given string and assigns it to the PortalBanner field.
func (o *V1EnterprisesPatchRequest) SetPortalBanner(v string) {
	o.PortalBanner = &v
}

// GetProxyTenantId returns the ProxyTenantId field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetProxyTenantId() int64 {
	if o == nil || IsNil(o.ProxyTenantId) {
		var ret int64
		return ret
	}
	return *o.ProxyTenantId
}

// GetProxyTenantIdOk returns a tuple with the ProxyTenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetProxyTenantIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ProxyTenantId) {
		return nil, false
	}
	return o.ProxyTenantId, true
}

// HasProxyTenantId returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasProxyTenantId() bool {
	if o != nil && !IsNil(o.ProxyTenantId) {
		return true
	}

	return false
}

// SetProxyTenantId gets a reference to the given int64 and assigns it to the ProxyTenantId field.
func (o *V1EnterprisesPatchRequest) SetProxyTenantId(v int64) {
	o.ProxyTenantId = &v
}

// GetSmallLogo returns the SmallLogo field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetSmallLogo() string {
	if o == nil || IsNil(o.SmallLogo) {
		var ret string
		return ret
	}
	return *o.SmallLogo
}

// GetSmallLogoOk returns a tuple with the SmallLogo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetSmallLogoOk() (*string, bool) {
	if o == nil || IsNil(o.SmallLogo) {
		return nil, false
	}
	return o.SmallLogo, true
}

// HasSmallLogo returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasSmallLogo() bool {
	if o != nil && !IsNil(o.SmallLogo) {
		return true
	}

	return false
}

// SetSmallLogo gets a reference to the given string and assigns it to the SmallLogo field.
func (o *V1EnterprisesPatchRequest) SetSmallLogo(v string) {
	o.SmallLogo = &v
}

// GetTokenExpiry returns the TokenExpiry field value if set, zero value otherwise.
func (o *V1EnterprisesPatchRequest) GetTokenExpiry() V1EnterprisesPatchRequestTokenExpiry {
	if o == nil || IsNil(o.TokenExpiry) {
		var ret V1EnterprisesPatchRequestTokenExpiry
		return ret
	}
	return *o.TokenExpiry
}

// GetTokenExpiryOk returns a tuple with the TokenExpiry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EnterprisesPatchRequest) GetTokenExpiryOk() (*V1EnterprisesPatchRequestTokenExpiry, bool) {
	if o == nil || IsNil(o.TokenExpiry) {
		return nil, false
	}
	return o.TokenExpiry, true
}

// HasTokenExpiry returns a boolean if a field has been set.
func (o *V1EnterprisesPatchRequest) HasTokenExpiry() bool {
	if o != nil && !IsNil(o.TokenExpiry) {
		return true
	}

	return false
}

// SetTokenExpiry gets a reference to the given V1EnterprisesPatchRequestTokenExpiry and assigns it to the TokenExpiry field.
func (o *V1EnterprisesPatchRequest) SetTokenExpiry(v V1EnterprisesPatchRequestTokenExpiry) {
	o.TokenExpiry = &v
}

func (o V1EnterprisesPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1EnterprisesPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdminEmail) {
		toSerialize["adminEmail"] = o.AdminEmail
	}
	if !IsNil(o.BackboneApisEnabled) {
		toSerialize["backboneApisEnabled"] = o.BackboneApisEnabled
	}
	if !IsNil(o.CloudProvider) {
		toSerialize["cloudProvider"] = o.CloudProvider
	}
	if !IsNil(o.CompanyName) {
		toSerialize["companyName"] = o.CompanyName
	}
	if !IsNil(o.CreditLimit) {
		toSerialize["creditLimit"] = o.CreditLimit
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.EnterpriseContract) {
		toSerialize["enterpriseContract"] = o.EnterpriseContract
	}
	toSerialize["enterpriseId"] = o.EnterpriseId
	if !IsNil(o.ImpersonationEnabled) {
		toSerialize["impersonationEnabled"] = o.ImpersonationEnabled
	}
	if !IsNil(o.Logo) {
		toSerialize["logo"] = o.Logo
	}
	if !IsNil(o.MarketplaceId) {
		toSerialize["marketplaceId"] = o.MarketplaceId
	}
	if !IsNil(o.PortalBanner) {
		toSerialize["portalBanner"] = o.PortalBanner
	}
	if !IsNil(o.ProxyTenantId) {
		toSerialize["proxyTenantId"] = o.ProxyTenantId
	}
	if !IsNil(o.SmallLogo) {
		toSerialize["smallLogo"] = o.SmallLogo
	}
	if !IsNil(o.TokenExpiry) {
		toSerialize["tokenExpiry"] = o.TokenExpiry
	}
	return toSerialize, nil
}

func (o *V1EnterprisesPatchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enterpriseId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1EnterprisesPatchRequest := _V1EnterprisesPatchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1EnterprisesPatchRequest)

	if err != nil {
		return err
	}

	*o = V1EnterprisesPatchRequest(varV1EnterprisesPatchRequest)

	return err
}

type NullableV1EnterprisesPatchRequest struct {
	value *V1EnterprisesPatchRequest
	isSet bool
}

func (v NullableV1EnterprisesPatchRequest) Get() *V1EnterprisesPatchRequest {
	return v.value
}

func (v *NullableV1EnterprisesPatchRequest) Set(val *V1EnterprisesPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1EnterprisesPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1EnterprisesPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1EnterprisesPatchRequest(val *V1EnterprisesPatchRequest) *NullableV1EnterprisesPatchRequest {
	return &NullableV1EnterprisesPatchRequest{value: val, isSet: true}
}

func (v NullableV1EnterprisesPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1EnterprisesPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


