/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookJobsJobIdApprovePutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookJobsJobIdApprovePutRequest{}

// V1SdkAutomationPlaybookJobsJobIdApprovePutRequest struct for V1SdkAutomationPlaybookJobsJobIdApprovePutRequest
type V1SdkAutomationPlaybookJobsJobIdApprovePutRequest struct {
	// When true, request ansible -vvv for the deploy phase
	VerboseLogs *bool `json:"verboseLogs,omitempty"`
}

// NewV1SdkAutomationPlaybookJobsJobIdApprovePutRequest instantiates a new V1SdkAutomationPlaybookJobsJobIdApprovePutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookJobsJobIdApprovePutRequest() *V1SdkAutomationPlaybookJobsJobIdApprovePutRequest {
	this := V1SdkAutomationPlaybookJobsJobIdApprovePutRequest{}
	return &this
}

// NewV1SdkAutomationPlaybookJobsJobIdApprovePutRequestWithDefaults instantiates a new V1SdkAutomationPlaybookJobsJobIdApprovePutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookJobsJobIdApprovePutRequestWithDefaults() *V1SdkAutomationPlaybookJobsJobIdApprovePutRequest {
	this := V1SdkAutomationPlaybookJobsJobIdApprovePutRequest{}
	return &this
}

// GetVerboseLogs returns the VerboseLogs field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookJobsJobIdApprovePutRequest) GetVerboseLogs() bool {
	if o == nil || IsNil(o.VerboseLogs) {
		var ret bool
		return ret
	}
	return *o.VerboseLogs
}

// GetVerboseLogsOk returns a tuple with the VerboseLogs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdApprovePutRequest) GetVerboseLogsOk() (*bool, bool) {
	if o == nil || IsNil(o.VerboseLogs) {
		return nil, false
	}
	return o.VerboseLogs, true
}

// HasVerboseLogs returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookJobsJobIdApprovePutRequest) HasVerboseLogs() bool {
	if o != nil && !IsNil(o.VerboseLogs) {
		return true
	}

	return false
}

// SetVerboseLogs gets a reference to the given bool and assigns it to the VerboseLogs field.
func (o *V1SdkAutomationPlaybookJobsJobIdApprovePutRequest) SetVerboseLogs(v bool) {
	o.VerboseLogs = &v
}

func (o V1SdkAutomationPlaybookJobsJobIdApprovePutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookJobsJobIdApprovePutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VerboseLogs) {
		toSerialize["verboseLogs"] = o.VerboseLogs
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookJobsJobIdApprovePutRequest struct {
	value *V1SdkAutomationPlaybookJobsJobIdApprovePutRequest
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdApprovePutRequest) Get() *V1SdkAutomationPlaybookJobsJobIdApprovePutRequest {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdApprovePutRequest) Set(val *V1SdkAutomationPlaybookJobsJobIdApprovePutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdApprovePutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdApprovePutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookJobsJobIdApprovePutRequest(val *V1SdkAutomationPlaybookJobsJobIdApprovePutRequest) *NullableV1SdkAutomationPlaybookJobsJobIdApprovePutRequest {
	return &NullableV1SdkAutomationPlaybookJobsJobIdApprovePutRequest{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookJobsJobIdApprovePutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookJobsJobIdApprovePutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


