/*
Graphiant APIs

Graphiant API documentation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graphiant_sdk

import (
	"encoding/json"
)

// checks if the V1SdkAutomationPlaybookConfigsPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SdkAutomationPlaybookConfigsPostRequest{}

// V1SdkAutomationPlaybookConfigsPostRequest struct for V1SdkAutomationPlaybookConfigsPostRequest
type V1SdkAutomationPlaybookConfigsPostRequest struct {
	// Catalog key from playbook_catalog_playbook (e.g. system_bundle)
	BundleKey *string `json:"bundleKey,omitempty"`
	Files []SdkAutomationModuleFile `json:"files,omitempty"`
	// When true, validate without persisting (Validate Bundle); when false, create on success
	ValidateOnly *bool `json:"validateOnly,omitempty"`
}

// NewV1SdkAutomationPlaybookConfigsPostRequest instantiates a new V1SdkAutomationPlaybookConfigsPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SdkAutomationPlaybookConfigsPostRequest() *V1SdkAutomationPlaybookConfigsPostRequest {
	this := V1SdkAutomationPlaybookConfigsPostRequest{}
	return &this
}

// NewV1SdkAutomationPlaybookConfigsPostRequestWithDefaults instantiates a new V1SdkAutomationPlaybookConfigsPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SdkAutomationPlaybookConfigsPostRequestWithDefaults() *V1SdkAutomationPlaybookConfigsPostRequest {
	this := V1SdkAutomationPlaybookConfigsPostRequest{}
	return &this
}

// GetBundleKey returns the BundleKey field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsPostRequest) GetBundleKey() string {
	if o == nil || IsNil(o.BundleKey) {
		var ret string
		return ret
	}
	return *o.BundleKey
}

// GetBundleKeyOk returns a tuple with the BundleKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsPostRequest) GetBundleKeyOk() (*string, bool) {
	if o == nil || IsNil(o.BundleKey) {
		return nil, false
	}
	return o.BundleKey, true
}

// HasBundleKey returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsPostRequest) HasBundleKey() bool {
	if o != nil && !IsNil(o.BundleKey) {
		return true
	}

	return false
}

// SetBundleKey gets a reference to the given string and assigns it to the BundleKey field.
func (o *V1SdkAutomationPlaybookConfigsPostRequest) SetBundleKey(v string) {
	o.BundleKey = &v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsPostRequest) GetFiles() []SdkAutomationModuleFile {
	if o == nil || IsNil(o.Files) {
		var ret []SdkAutomationModuleFile
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsPostRequest) GetFilesOk() ([]SdkAutomationModuleFile, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsPostRequest) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []SdkAutomationModuleFile and assigns it to the Files field.
func (o *V1SdkAutomationPlaybookConfigsPostRequest) SetFiles(v []SdkAutomationModuleFile) {
	o.Files = v
}

// GetValidateOnly returns the ValidateOnly field value if set, zero value otherwise.
func (o *V1SdkAutomationPlaybookConfigsPostRequest) GetValidateOnly() bool {
	if o == nil || IsNil(o.ValidateOnly) {
		var ret bool
		return ret
	}
	return *o.ValidateOnly
}

// GetValidateOnlyOk returns a tuple with the ValidateOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SdkAutomationPlaybookConfigsPostRequest) GetValidateOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.ValidateOnly) {
		return nil, false
	}
	return o.ValidateOnly, true
}

// HasValidateOnly returns a boolean if a field has been set.
func (o *V1SdkAutomationPlaybookConfigsPostRequest) HasValidateOnly() bool {
	if o != nil && !IsNil(o.ValidateOnly) {
		return true
	}

	return false
}

// SetValidateOnly gets a reference to the given bool and assigns it to the ValidateOnly field.
func (o *V1SdkAutomationPlaybookConfigsPostRequest) SetValidateOnly(v bool) {
	o.ValidateOnly = &v
}

func (o V1SdkAutomationPlaybookConfigsPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SdkAutomationPlaybookConfigsPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BundleKey) {
		toSerialize["bundleKey"] = o.BundleKey
	}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	if !IsNil(o.ValidateOnly) {
		toSerialize["validateOnly"] = o.ValidateOnly
	}
	return toSerialize, nil
}

type NullableV1SdkAutomationPlaybookConfigsPostRequest struct {
	value *V1SdkAutomationPlaybookConfigsPostRequest
	isSet bool
}

func (v NullableV1SdkAutomationPlaybookConfigsPostRequest) Get() *V1SdkAutomationPlaybookConfigsPostRequest {
	return v.value
}

func (v *NullableV1SdkAutomationPlaybookConfigsPostRequest) Set(val *V1SdkAutomationPlaybookConfigsPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SdkAutomationPlaybookConfigsPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SdkAutomationPlaybookConfigsPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SdkAutomationPlaybookConfigsPostRequest(val *V1SdkAutomationPlaybookConfigsPostRequest) *NullableV1SdkAutomationPlaybookConfigsPostRequest {
	return &NullableV1SdkAutomationPlaybookConfigsPostRequest{value: val, isSet: true}
}

func (v NullableV1SdkAutomationPlaybookConfigsPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SdkAutomationPlaybookConfigsPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


